#ifndef LTC_DEFINES_H
#define LTC_DEFINES_H

#define SET_MODE_RSP_ERROR_LEN 25

#define TEMP_RSLT_COUNT 4

typedef enum {
	SINGLE_MODE,
	CONTINUOUS_MODE,
	STOP_MODE,
	STARTUP_MODE
} LTC2983_AppMeasurementMode;

typedef enum {
	RESULT_READY,
	RESULT_NOT_READY
} LTC2983_AppMeasureReady;

typedef enum {
	STATUS_GOOD,
	STATUS_BAD
} SET_MODE_RPL_STATUS;

static const int validChannelList[4] = {
  4, 6, 8, 10
};

typedef enum {
	LTC2983_APPERROR_NONE,
	LTC2983_APPERROR_STARTUP,
	LTC2983_APPERROR_CONFIG,
	LTC2983_APPERROR_CONVERT,
	LTC2983_APPERROR_CONVERT_TIMEOUT,
	LTC2983_APPERROR_READ,
	LTC2983_APPERROR_READ_TIMEOUT,
	LTC2983_APPERROR_MUTEX,
} LTC2983_AppErrorState_t;

#endif /* LTC_DEFINES_H */
