/**
 * Payload specs module LTC
 * 
 * Generated by lpldgen 1.4.6
 */

#ifndef PLD_LTC_H
#define PLD_LTC_H

#include <payloads.h>

extern const struct pld_module Payloads_LTC;

/**
 * Payload variants in this module
 */
enum LTC_PayloadType {
    LTC_SET_MODE_REQ_ID = 1,
    LTC_SET_MODE_RSP_ID = 2,
    LTC_GET_STATUS_REQ_ID = 3,
    LTC_GET_STATUS_RSP_ID = 4,
    LTC_READ_TEMP_REQ_ID = 5,
    LTC_READ_TEMP_RSP_ID = 6,
    LTC_SET_RSENSE_REQ_ID = 7,
    LTC_SET_RSENSE_RSP_ID = 8,
    LTC_CHANGE_CHNL_CFG_REQ_ID = 9,
    LTC_CHANGE_CHNL_CFG_RSP_ID = 10
};

/** @defgroup spec_pointers Payload specifications
 *
 * Pointers into the spec look-up table, can be used to easily reference a pld_spec instance.
 *
 * @{
 */

extern const struct pld_spec * const PldSpec_LTC_SET_MODE_REQ;
extern const struct pld_spec * const PldSpec_LTC_SET_MODE_RSP;
extern const struct pld_spec * const PldSpec_LTC_GET_STATUS_REQ;
extern const struct pld_spec * const PldSpec_LTC_GET_STATUS_RSP;
extern const struct pld_spec * const PldSpec_LTC_READ_TEMP_REQ;
extern const struct pld_spec * const PldSpec_LTC_READ_TEMP_RSP;
extern const struct pld_spec * const PldSpec_LTC_SET_RSENSE_REQ;
extern const struct pld_spec * const PldSpec_LTC_SET_RSENSE_RSP;
extern const struct pld_spec * const PldSpec_LTC_CHANGE_CHNL_CFG_REQ;
extern const struct pld_spec * const PldSpec_LTC_CHANGE_CHNL_CFG_RSP;

/** @}*/

/** @defgroup payloads_structs Payload structs
 *
 * These structs represent payloads that can be packed to and unpacked from a binary format.
 *
 * Each struct is accompanied by its building and parsing function.
 *
 * @{
 */

/**
 * Payload "SET_MODE_REQ"
 *
 * Set measurement mode / ask for status
 */
struct LTC_SET_MODE_REQ {
    uint16_t pld_id; //!< Payload ID
    /** Set flags for reading temps */
    uint8_t mode;
    /** A flag to know if you are sending a frequency too */
    uint8_t set_frequency;
    /** Continuous measurement frequency */
    uint32_t frequency;
};

/* Associated constant values */

#define LTC_SET_MODE_REQ_CMD_ID 0

/** sizeof(SET_MODE_REQ) */
#define LTC_SET_MODE_REQ_C_SIZE (sizeof(struct LTC_SET_MODE_REQ))

/** Byte size of LTC_SET_MODE_REQ in binary form */
#define LTC_SET_MODE_REQ_BIN_SIZE 7

/** Payload LTC_SET_MODE_REQ CSP destination address */
#define LTC_SET_MODE_REQ_DST_ADDR 13

/** Payload LTC_SET_MODE_REQ CSP destination port */
#define LTC_SET_MODE_REQ_DST_PORT 10

/**
 * Payload "SET_MODE_RSP"
 *
 * jeden command na set, jeden na read, flagy -s -c -t <cislo> a spol a podle bit masky se bude zjistovat
 * Set mode response
 */
struct LTC_SET_MODE_RSP {
    uint16_t pld_id; //!< Payload ID
    /** Whether the setting was valid or not */
    uint8_t status;
    /** In case of an error an error message */
    int8_t error[25];
};

/* Associated constant values */

#define LTC_SET_MODE_RSP_CMD_ID 0

/** sizeof(SET_MODE_RSP) */
#define LTC_SET_MODE_RSP_C_SIZE (sizeof(struct LTC_SET_MODE_RSP))

/** Byte size of LTC_SET_MODE_RSP in binary form */
#define LTC_SET_MODE_RSP_BIN_SIZE 27

/** Payload LTC_SET_MODE_RSP CSP source address */
#define LTC_SET_MODE_RSP_SRC_ADDR 13

/** Payload LTC_SET_MODE_RSP CSP source port */
#define LTC_SET_MODE_RSP_SRC_PORT 10

/**
 * Payload "GET_STATUS_REQ"
 *
 * Get status, mode and frequency request
 */
struct LTC_GET_STATUS_REQ {
    uint16_t pld_id; //!< Payload ID
    /* empty */
};

/* Associated constant values */

#define LTC_GET_STATUS_REQ_CMD_ID 1

/** sizeof(GET_STATUS_REQ) */
#define LTC_GET_STATUS_REQ_C_SIZE (sizeof(struct LTC_GET_STATUS_REQ))

/** Byte size of LTC_GET_STATUS_REQ in binary form */
#define LTC_GET_STATUS_REQ_BIN_SIZE 1

/** Payload LTC_GET_STATUS_REQ CSP destination address */
#define LTC_GET_STATUS_REQ_DST_ADDR 13

/** Payload LTC_GET_STATUS_REQ CSP destination port */
#define LTC_GET_STATUS_REQ_DST_PORT 10

/**
 * Payload "GET_STATUS_RSP"
 *
 * Get mode and frequency response
 */
struct LTC_GET_STATUS_RSP {
    uint16_t pld_id; //!< Payload ID
    /** Active mode */
    uint8_t mode;
    /** Result status */
    uint8_t result_status;
    /** Continuous measurement frequency */
    uint32_t frequency;
    /** Error code */
    uint8_t error;
};

/* Associated constant values */

#define LTC_GET_STATUS_RSP_CMD_ID 1

/** sizeof(GET_STATUS_RSP) */
#define LTC_GET_STATUS_RSP_C_SIZE (sizeof(struct LTC_GET_STATUS_RSP))

/** Byte size of LTC_GET_STATUS_RSP in binary form */
#define LTC_GET_STATUS_RSP_BIN_SIZE 8

/** Payload LTC_GET_STATUS_RSP CSP source address */
#define LTC_GET_STATUS_RSP_SRC_ADDR 13

/** Payload LTC_GET_STATUS_RSP CSP source port */
#define LTC_GET_STATUS_RSP_SRC_PORT 10

/**
 * Payload "READ_TEMP_REQ"
 *
 * LTC2983 read temperature request
 */
struct LTC_READ_TEMP_REQ {
    uint16_t pld_id; //!< Payload ID
    /** Target channel ID */
    uint8_t channel_id;
    /** Forces a new measurement if results are not ready */
    uint8_t force_measurement;
};

/* Associated constant values */

#define LTC_READ_TEMP_REQ_CMD_ID 2

/** sizeof(READ_TEMP_REQ) */
#define LTC_READ_TEMP_REQ_C_SIZE (sizeof(struct LTC_READ_TEMP_REQ))

/** Byte size of LTC_READ_TEMP_REQ in binary form */
#define LTC_READ_TEMP_REQ_BIN_SIZE 3

/** Payload LTC_READ_TEMP_REQ CSP destination address */
#define LTC_READ_TEMP_REQ_DST_ADDR 13

/** Payload LTC_READ_TEMP_REQ CSP destination port */
#define LTC_READ_TEMP_REQ_DST_PORT 10

/**
 * Payload "READ_TEMP_RSP"
 *
 * LTC2983 read temperature response
 */
struct LTC_READ_TEMP_RSP {
    uint16_t pld_id; //!< Payload ID
    uint8_t result_ready;
    struct {
        /** Channel ID */
        uint8_t channel;
        /** Status of the reading */
        uint8_t status;
        /** Temperature */
        float temperature;
        /** Raw Voltage */
        float raw;
    } TempRslt[20];
};

/* Associated constant values */

#define LTC_READ_TEMP_RSP_CMD_ID 2

/** sizeof(READ_TEMP_RSP) */
#define LTC_READ_TEMP_RSP_C_SIZE (sizeof(struct LTC_READ_TEMP_RSP))

/** Byte size of LTC_READ_TEMP_RSP in binary form */
#define LTC_READ_TEMP_RSP_BIN_SIZE 202

/** Payload LTC_READ_TEMP_RSP CSP source address */
#define LTC_READ_TEMP_RSP_SRC_ADDR 13

/** Payload LTC_READ_TEMP_RSP CSP source port */
#define LTC_READ_TEMP_RSP_SRC_PORT 10

/**
 * Payload "SET_RSENSE_REQ"
 *
 * Set rsense value
 */
struct LTC_SET_RSENSE_REQ {
    uint16_t pld_id; //!< Payload ID
    /** Rsense value to set */
    float val;
};

/* Associated constant values */

#define LTC_SET_RSENSE_REQ_CMD_ID 3

/** sizeof(SET_RSENSE_REQ) */
#define LTC_SET_RSENSE_REQ_C_SIZE (sizeof(struct LTC_SET_RSENSE_REQ))

/** Byte size of LTC_SET_RSENSE_REQ in binary form */
#define LTC_SET_RSENSE_REQ_BIN_SIZE 5

/** Payload LTC_SET_RSENSE_REQ CSP destination address */
#define LTC_SET_RSENSE_REQ_DST_ADDR 13

/** Payload LTC_SET_RSENSE_REQ CSP destination port */
#define LTC_SET_RSENSE_REQ_DST_PORT 10

/**
 * Payload "SET_RSENSE_RSP"
 *
 * Set rsense value response
 */
struct LTC_SET_RSENSE_RSP {
    uint16_t pld_id; //!< Payload ID
    /* empty */
};

/* Associated constant values */

#define LTC_SET_RSENSE_RSP_CMD_ID 3

/** sizeof(SET_RSENSE_RSP) */
#define LTC_SET_RSENSE_RSP_C_SIZE (sizeof(struct LTC_SET_RSENSE_RSP))

/** Byte size of LTC_SET_RSENSE_RSP in binary form */
#define LTC_SET_RSENSE_RSP_BIN_SIZE 1

/** Payload LTC_SET_RSENSE_RSP CSP source address */
#define LTC_SET_RSENSE_RSP_SRC_ADDR 13

/** Payload LTC_SET_RSENSE_RSP CSP source port */
#define LTC_SET_RSENSE_RSP_SRC_PORT 10

/**
 * Payload "CHANGE_CHNL_CFG_REQ"
 *
 * Change channel config request
 */
struct LTC_CHANGE_CHNL_CFG_REQ {
    uint16_t pld_id; //!< Payload ID
    /** A flag to reset channel to its original config */
    uint8_t reset;
    /** Target channel to change config on */
    uint8_t channel;
    /** Desired config values */
    uint32_t cfg;
};

/* Associated constant values */

#define LTC_CHANGE_CHNL_CFG_REQ_CMD_ID 4

/** sizeof(CHANGE_CHNL_CFG_REQ) */
#define LTC_CHANGE_CHNL_CFG_REQ_C_SIZE (sizeof(struct LTC_CHANGE_CHNL_CFG_REQ))

/** Byte size of LTC_CHANGE_CHNL_CFG_REQ in binary form */
#define LTC_CHANGE_CHNL_CFG_REQ_BIN_SIZE 7

/** Payload LTC_CHANGE_CHNL_CFG_REQ CSP destination address */
#define LTC_CHANGE_CHNL_CFG_REQ_DST_ADDR 13

/** Payload LTC_CHANGE_CHNL_CFG_REQ CSP destination port */
#define LTC_CHANGE_CHNL_CFG_REQ_DST_PORT 10

/** Payload "CHANGE_CHNL_CFG_RSP" */
struct LTC_CHANGE_CHNL_CFG_RSP {
    uint16_t pld_id; //!< Payload ID
    uint8_t rsp;
};

/* Associated constant values */

#define LTC_CHANGE_CHNL_CFG_RSP_CMD_ID 4

/** sizeof(CHANGE_CHNL_CFG_RSP) */
#define LTC_CHANGE_CHNL_CFG_RSP_C_SIZE (sizeof(struct LTC_CHANGE_CHNL_CFG_RSP))

/** Byte size of LTC_CHANGE_CHNL_CFG_RSP in binary form */
#define LTC_CHANGE_CHNL_CFG_RSP_BIN_SIZE 2

/** Payload LTC_CHANGE_CHNL_CFG_RSP CSP source address */
#define LTC_CHANGE_CHNL_CFG_RSP_SRC_ADDR 13

/** Payload LTC_CHANGE_CHNL_CFG_RSP CSP source port */
#define LTC_CHANGE_CHNL_CFG_RSP_SRC_PORT 10

/** @}*/

/** @defgroup payloads_parsing Payload parsing
 *
 * Functions converting payload structs from their binary forms.
 *
 * All payload parsing functions share this signature:
 *
 * - <b>payload (in)</b> … a byte buffer to parse (e.g. received from CSP)
 * - <b>length (in)</b> … length of the payload buffer
 * - <b>alloc (in)</b> … allocator, malloc-like function used to allocate the output struct.
 *   The caller is responsible for disposing of the struct accordingly.
 * - <b>output (out)</b> … destination pointer, the parsed struct is output here
 *
 * The returned status code should be checked for errors.
 * @{
 */

#if PLD_HAVE_ALLOC
/** @brief Parse a binary payload into the "SET_MODE_REQ" payload struct. */
pld_error_t LTC_SET_MODE_REQ_parse(const uint8_t *payload, size_t length, pld_alloc_fn alloc, struct LTC_SET_MODE_REQ **output);
#endif /* PLD_HAVE_ALLOC */

/** @brief Parse a binary payload into the "SET_MODE_REQ" payload struct (static version) */
pld_error_t LTC_SET_MODE_REQ_parse_s(const uint8_t *payload, size_t length, struct LTC_SET_MODE_REQ *output);

#if PLD_HAVE_ALLOC
/** @brief Parse a binary payload into the "SET_MODE_RSP" payload struct. */
pld_error_t LTC_SET_MODE_RSP_parse(const uint8_t *payload, size_t length, pld_alloc_fn alloc, struct LTC_SET_MODE_RSP **output);
#endif /* PLD_HAVE_ALLOC */

/** @brief Parse a binary payload into the "SET_MODE_RSP" payload struct (static version) */
pld_error_t LTC_SET_MODE_RSP_parse_s(const uint8_t *payload, size_t length, struct LTC_SET_MODE_RSP *output);

#if PLD_HAVE_ALLOC
/** @brief Parse a binary payload into the "GET_STATUS_REQ" payload struct. */
pld_error_t LTC_GET_STATUS_REQ_parse(const uint8_t *payload, size_t length, pld_alloc_fn alloc, struct LTC_GET_STATUS_REQ **output);
#endif /* PLD_HAVE_ALLOC */

/** @brief Parse a binary payload into the "GET_STATUS_REQ" payload struct (static version) */
pld_error_t LTC_GET_STATUS_REQ_parse_s(const uint8_t *payload, size_t length, struct LTC_GET_STATUS_REQ *output);

#if PLD_HAVE_ALLOC
/** @brief Parse a binary payload into the "GET_STATUS_RSP" payload struct. */
pld_error_t LTC_GET_STATUS_RSP_parse(const uint8_t *payload, size_t length, pld_alloc_fn alloc, struct LTC_GET_STATUS_RSP **output);
#endif /* PLD_HAVE_ALLOC */

/** @brief Parse a binary payload into the "GET_STATUS_RSP" payload struct (static version) */
pld_error_t LTC_GET_STATUS_RSP_parse_s(const uint8_t *payload, size_t length, struct LTC_GET_STATUS_RSP *output);

#if PLD_HAVE_ALLOC
/** @brief Parse a binary payload into the "READ_TEMP_REQ" payload struct. */
pld_error_t LTC_READ_TEMP_REQ_parse(const uint8_t *payload, size_t length, pld_alloc_fn alloc, struct LTC_READ_TEMP_REQ **output);
#endif /* PLD_HAVE_ALLOC */

/** @brief Parse a binary payload into the "READ_TEMP_REQ" payload struct (static version) */
pld_error_t LTC_READ_TEMP_REQ_parse_s(const uint8_t *payload, size_t length, struct LTC_READ_TEMP_REQ *output);

#if PLD_HAVE_ALLOC
/** @brief Parse a binary payload into the "READ_TEMP_RSP" payload struct. */
pld_error_t LTC_READ_TEMP_RSP_parse(const uint8_t *payload, size_t length, pld_alloc_fn alloc, struct LTC_READ_TEMP_RSP **output);
#endif /* PLD_HAVE_ALLOC */

/** @brief Parse a binary payload into the "READ_TEMP_RSP" payload struct (static version) */
pld_error_t LTC_READ_TEMP_RSP_parse_s(const uint8_t *payload, size_t length, struct LTC_READ_TEMP_RSP *output);

#if PLD_HAVE_ALLOC
/** @brief Parse a binary payload into the "SET_RSENSE_REQ" payload struct. */
pld_error_t LTC_SET_RSENSE_REQ_parse(const uint8_t *payload, size_t length, pld_alloc_fn alloc, struct LTC_SET_RSENSE_REQ **output);
#endif /* PLD_HAVE_ALLOC */

/** @brief Parse a binary payload into the "SET_RSENSE_REQ" payload struct (static version) */
pld_error_t LTC_SET_RSENSE_REQ_parse_s(const uint8_t *payload, size_t length, struct LTC_SET_RSENSE_REQ *output);

#if PLD_HAVE_ALLOC
/** @brief Parse a binary payload into the "SET_RSENSE_RSP" payload struct. */
pld_error_t LTC_SET_RSENSE_RSP_parse(const uint8_t *payload, size_t length, pld_alloc_fn alloc, struct LTC_SET_RSENSE_RSP **output);
#endif /* PLD_HAVE_ALLOC */

/** @brief Parse a binary payload into the "SET_RSENSE_RSP" payload struct (static version) */
pld_error_t LTC_SET_RSENSE_RSP_parse_s(const uint8_t *payload, size_t length, struct LTC_SET_RSENSE_RSP *output);

#if PLD_HAVE_ALLOC
/** @brief Parse a binary payload into the "CHANGE_CHNL_CFG_REQ" payload struct. */
pld_error_t LTC_CHANGE_CHNL_CFG_REQ_parse(const uint8_t *payload, size_t length, pld_alloc_fn alloc, struct LTC_CHANGE_CHNL_CFG_REQ **output);
#endif /* PLD_HAVE_ALLOC */

/** @brief Parse a binary payload into the "CHANGE_CHNL_CFG_REQ" payload struct (static version) */
pld_error_t LTC_CHANGE_CHNL_CFG_REQ_parse_s(const uint8_t *payload, size_t length, struct LTC_CHANGE_CHNL_CFG_REQ *output);

#if PLD_HAVE_ALLOC
/** @brief Parse a binary payload into the "CHANGE_CHNL_CFG_RSP" payload struct. */
pld_error_t LTC_CHANGE_CHNL_CFG_RSP_parse(const uint8_t *payload, size_t length, pld_alloc_fn alloc, struct LTC_CHANGE_CHNL_CFG_RSP **output);
#endif /* PLD_HAVE_ALLOC */

/** @brief Parse a binary payload into the "CHANGE_CHNL_CFG_RSP" payload struct (static version) */
pld_error_t LTC_CHANGE_CHNL_CFG_RSP_parse_s(const uint8_t *payload, size_t length, struct LTC_CHANGE_CHNL_CFG_RSP *output);

/** @}*/

/** @defgroup payloads_building Payload building
 *
 * Functions converting payload structs into their binary forms.
 *
 * All payload building functions share this signature:
 *
 * - <b>data (in)</b> … the payload struct to read data from
 * - <b>alloc (in)</b> … allocator, malloc-like function called to obtain a byte buffer.
 *   The caller is responsible for disposing of the buffer accordingly.
 * - <b>output (out)</b> … destination pointer, the byte buffer is output here
 * - <b>len (out,optional)</b> … length of the output buffer is stored here (may be NULL if not needed)
 *
 * The returned status code should be checked for errors.
 * @{
 */

#if PLD_HAVE_ALLOC
/** @brief Encode payload struct "SET_MODE_REQ" to its binary form. */
pld_error_t LTC_SET_MODE_REQ_build(const struct LTC_SET_MODE_REQ *data, pld_alloc_fn alloc, uint8_t **output, size_t *len);
#endif /* PLD_HAVE_ALLOC */

/** @brief Encode payload struct "SET_MODE_REQ" to its binary form. (static version) */
pld_error_t LTC_SET_MODE_REQ_build_s(const struct LTC_SET_MODE_REQ *data, uint8_t *output, size_t capacity);

#if PLD_HAVE_ALLOC
/** @brief Encode payload struct "SET_MODE_RSP" to its binary form. */
pld_error_t LTC_SET_MODE_RSP_build(const struct LTC_SET_MODE_RSP *data, pld_alloc_fn alloc, uint8_t **output, size_t *len);
#endif /* PLD_HAVE_ALLOC */

/** @brief Encode payload struct "SET_MODE_RSP" to its binary form. (static version) */
pld_error_t LTC_SET_MODE_RSP_build_s(const struct LTC_SET_MODE_RSP *data, uint8_t *output, size_t capacity);

#if PLD_HAVE_ALLOC
/** @brief Encode payload struct "GET_STATUS_REQ" to its binary form. Data may be NULL. */
pld_error_t LTC_GET_STATUS_REQ_build(const struct LTC_GET_STATUS_REQ *data, pld_alloc_fn alloc, uint8_t **output, size_t *len);
#endif /* PLD_HAVE_ALLOC */

/** @brief Encode payload struct "GET_STATUS_REQ" to its binary form. Data may be NULL. (static version) */
pld_error_t LTC_GET_STATUS_REQ_build_s(const struct LTC_GET_STATUS_REQ *data, uint8_t *output, size_t capacity);

#if PLD_HAVE_ALLOC
/** @brief Encode payload struct "GET_STATUS_RSP" to its binary form. */
pld_error_t LTC_GET_STATUS_RSP_build(const struct LTC_GET_STATUS_RSP *data, pld_alloc_fn alloc, uint8_t **output, size_t *len);
#endif /* PLD_HAVE_ALLOC */

/** @brief Encode payload struct "GET_STATUS_RSP" to its binary form. (static version) */
pld_error_t LTC_GET_STATUS_RSP_build_s(const struct LTC_GET_STATUS_RSP *data, uint8_t *output, size_t capacity);

#if PLD_HAVE_ALLOC
/** @brief Encode payload struct "READ_TEMP_REQ" to its binary form. */
pld_error_t LTC_READ_TEMP_REQ_build(const struct LTC_READ_TEMP_REQ *data, pld_alloc_fn alloc, uint8_t **output, size_t *len);
#endif /* PLD_HAVE_ALLOC */

/** @brief Encode payload struct "READ_TEMP_REQ" to its binary form. (static version) */
pld_error_t LTC_READ_TEMP_REQ_build_s(const struct LTC_READ_TEMP_REQ *data, uint8_t *output, size_t capacity);

#if PLD_HAVE_ALLOC
/** @brief Encode payload struct "READ_TEMP_RSP" to its binary form. */
pld_error_t LTC_READ_TEMP_RSP_build(const struct LTC_READ_TEMP_RSP *data, pld_alloc_fn alloc, uint8_t **output, size_t *len);
#endif /* PLD_HAVE_ALLOC */

/** @brief Encode payload struct "READ_TEMP_RSP" to its binary form. (static version) */
pld_error_t LTC_READ_TEMP_RSP_build_s(const struct LTC_READ_TEMP_RSP *data, uint8_t *output, size_t capacity);

#if PLD_HAVE_ALLOC
/** @brief Encode payload struct "SET_RSENSE_REQ" to its binary form. */
pld_error_t LTC_SET_RSENSE_REQ_build(const struct LTC_SET_RSENSE_REQ *data, pld_alloc_fn alloc, uint8_t **output, size_t *len);
#endif /* PLD_HAVE_ALLOC */

/** @brief Encode payload struct "SET_RSENSE_REQ" to its binary form. (static version) */
pld_error_t LTC_SET_RSENSE_REQ_build_s(const struct LTC_SET_RSENSE_REQ *data, uint8_t *output, size_t capacity);

#if PLD_HAVE_ALLOC
/** @brief Encode payload struct "SET_RSENSE_RSP" to its binary form. Data may be NULL. */
pld_error_t LTC_SET_RSENSE_RSP_build(const struct LTC_SET_RSENSE_RSP *data, pld_alloc_fn alloc, uint8_t **output, size_t *len);
#endif /* PLD_HAVE_ALLOC */

/** @brief Encode payload struct "SET_RSENSE_RSP" to its binary form. Data may be NULL. (static version) */
pld_error_t LTC_SET_RSENSE_RSP_build_s(const struct LTC_SET_RSENSE_RSP *data, uint8_t *output, size_t capacity);

#if PLD_HAVE_ALLOC
/** @brief Encode payload struct "CHANGE_CHNL_CFG_REQ" to its binary form. */
pld_error_t LTC_CHANGE_CHNL_CFG_REQ_build(const struct LTC_CHANGE_CHNL_CFG_REQ *data, pld_alloc_fn alloc, uint8_t **output, size_t *len);
#endif /* PLD_HAVE_ALLOC */

/** @brief Encode payload struct "CHANGE_CHNL_CFG_REQ" to its binary form. (static version) */
pld_error_t LTC_CHANGE_CHNL_CFG_REQ_build_s(const struct LTC_CHANGE_CHNL_CFG_REQ *data, uint8_t *output, size_t capacity);

#if PLD_HAVE_ALLOC
/** @brief Encode payload struct "CHANGE_CHNL_CFG_RSP" to its binary form. */
pld_error_t LTC_CHANGE_CHNL_CFG_RSP_build(const struct LTC_CHANGE_CHNL_CFG_RSP *data, pld_alloc_fn alloc, uint8_t **output, size_t *len);
#endif /* PLD_HAVE_ALLOC */

/** @brief Encode payload struct "CHANGE_CHNL_CFG_RSP" to its binary form. (static version) */
pld_error_t LTC_CHANGE_CHNL_CFG_RSP_build_s(const struct LTC_CHANGE_CHNL_CFG_RSP *data, uint8_t *output, size_t capacity);

/** @}*/

#if PLD_HAVE_EXPORT
/** @defgroup payloads_building Payload building
 *
 * Functions converting payload structs into JSON.
 *
 * All payload export functions share this signature:
 *
 * - <b>data (in)</b> … the payload struct to read data from
 * - <b>style (in)</b> … JSON variant (EXPORT_JSON_DATAONLY, EXPORT_JSON_ANNOTATED)
 * - <b>output (out)</b> … destination pointer, the json is output here
 *
 * The returned status code should be checked for errors.
 * @{
 */

/** @brief Export payload struct "SET_MODE_REQ" to JSON (without look-up) */
pld_error_t LTC_SET_MODE_REQ_to_json(const struct LTC_SET_MODE_REQ *data, enum pld_export_json_style style, cJSON** output);

/** @brief Export payload struct "SET_MODE_RSP" to JSON (without look-up) */
pld_error_t LTC_SET_MODE_RSP_to_json(const struct LTC_SET_MODE_RSP *data, enum pld_export_json_style style, cJSON** output);

/** @brief Export payload struct "GET_STATUS_REQ" to JSON (without look-up) */
pld_error_t LTC_GET_STATUS_REQ_to_json(const struct LTC_GET_STATUS_REQ *data, enum pld_export_json_style style, cJSON** output);

/** @brief Export payload struct "GET_STATUS_RSP" to JSON (without look-up) */
pld_error_t LTC_GET_STATUS_RSP_to_json(const struct LTC_GET_STATUS_RSP *data, enum pld_export_json_style style, cJSON** output);

/** @brief Export payload struct "READ_TEMP_REQ" to JSON (without look-up) */
pld_error_t LTC_READ_TEMP_REQ_to_json(const struct LTC_READ_TEMP_REQ *data, enum pld_export_json_style style, cJSON** output);

/** @brief Export payload struct "READ_TEMP_RSP" to JSON (without look-up) */
pld_error_t LTC_READ_TEMP_RSP_to_json(const struct LTC_READ_TEMP_RSP *data, enum pld_export_json_style style, cJSON** output);

/** @brief Export payload struct "SET_RSENSE_REQ" to JSON (without look-up) */
pld_error_t LTC_SET_RSENSE_REQ_to_json(const struct LTC_SET_RSENSE_REQ *data, enum pld_export_json_style style, cJSON** output);

/** @brief Export payload struct "SET_RSENSE_RSP" to JSON (without look-up) */
pld_error_t LTC_SET_RSENSE_RSP_to_json(const struct LTC_SET_RSENSE_RSP *data, enum pld_export_json_style style, cJSON** output);

/** @brief Export payload struct "CHANGE_CHNL_CFG_REQ" to JSON (without look-up) */
pld_error_t LTC_CHANGE_CHNL_CFG_REQ_to_json(const struct LTC_CHANGE_CHNL_CFG_REQ *data, enum pld_export_json_style style, cJSON** output);

/** @brief Export payload struct "CHANGE_CHNL_CFG_RSP" to JSON (without look-up) */
pld_error_t LTC_CHANGE_CHNL_CFG_RSP_to_json(const struct LTC_CHANGE_CHNL_CFG_RSP *data, enum pld_export_json_style style, cJSON** output);

/** @}*/
#endif /* PLD_HAVE_EXPORT */

#endif /* PLD_LTC_H */
