/**
 * Payload specs module Driver_Template
 * 
 * Generated by lpldgen 1.4.6
 */

#ifndef PLD_DRIVER_TEMPLATE_H
#define PLD_DRIVER_TEMPLATE_H

#include <pld/payloads.h>

extern const struct pld_module Payloads_Driver_Template;

/**
 * Payload variants in this module
 */
enum Driver_Template_PayloadType {
    DRIVER_TEMPLATE_PING_ID = 1,
    DRIVER_TEMPLATE_PONG_ID = 2,
    DRIVER_TEMPLATE_ECHO_REQ_ID = 3,
    DRIVER_TEMPLATE_ECHO_RPL_ID = 4,
    DRIVER_TEMPLATE_KILL_ID = 5
};

/** @defgroup spec_pointers Payload specifications
 *
 * Pointers into the spec look-up table, can be used to easily reference a pld_spec instance.
 *
 * @{
 */

extern const struct pld_spec * const PldSpec_Driver_Template_Ping;
extern const struct pld_spec * const PldSpec_Driver_Template_Pong;
extern const struct pld_spec * const PldSpec_Driver_Template_Echo_Req;
extern const struct pld_spec * const PldSpec_Driver_Template_Echo_Rpl;
extern const struct pld_spec * const PldSpec_Driver_Template_Kill;

/** @}*/

/** @defgroup payloads_structs Payload structs
 *
 * These structs represent payloads that can be packed to and unpacked from a binary format.
 *
 * Each struct is accompanied by its building and parsing function.
 *
 * @{
 */

/**
 * Payload "Ping"
 *
 * Example ping request to CSP node 1, port 2 (custom one, not the CSP built-in ping)
 */
struct Driver_Template_Ping {
    uint16_t pld_id; //!< Payload ID
    /* empty */
};

/* Associated constant values */

#define DRIVER_TEMPLATE_PING_CMD_ID 0

/** sizeof(Ping) */
#define DRIVER_TEMPLATE_PING_C_SIZE (sizeof(struct Driver_Template_Ping))

/** Byte size of Driver_Template_Ping in binary form */
#define DRIVER_TEMPLATE_PING_BIN_SIZE 1

/** Payload Driver_Template_Ping CSP destination address */
#define DRIVER_TEMPLATE_PING_DST_ADDR 1

/** Payload Driver_Template_Ping CSP destination port */
#define DRIVER_TEMPLATE_PING_DST_PORT 2

/**
 * Payload "Pong"
 *
 * Reply to the ping request
 */
struct Driver_Template_Pong {
    uint16_t pld_id; //!< Payload ID
    int8_t text[16];
};

/* Associated constant values */

#define DRIVER_TEMPLATE_PONG_CMD_ID 0

/** sizeof(Pong) */
#define DRIVER_TEMPLATE_PONG_C_SIZE (sizeof(struct Driver_Template_Pong))

/** Byte size of Driver_Template_Pong in binary form */
#define DRIVER_TEMPLATE_PONG_BIN_SIZE 17

/** Payload Driver_Template_Pong CSP source address */
#define DRIVER_TEMPLATE_PONG_SRC_ADDR 1

/** Payload Driver_Template_Pong CSP source port */
#define DRIVER_TEMPLATE_PONG_SRC_PORT 2

/**
 * Payload "Echo_Req"
 *
 * Example echo request
 */
struct Driver_Template_Echo_Req {
    uint16_t pld_id; //!< Payload ID
    size_t text_len; //!< Length of the "text"
    int8_t text[];
};

/* Associated constant values */

#define DRIVER_TEMPLATE_ECHO_REQ_CMD_ID 1

/** sizeof(Echo_Req) with a tail of given size */
#define DRIVER_TEMPLATE_ECHO_REQ_TAIL_ELEM_C_SIZE sizeof(((struct Driver_Template_Echo_Req*)0)->text[0])

/** sizeof(Echo_Req) with a tail of given size */
#define DRIVER_TEMPLATE_ECHO_REQ_C_SIZE(_tail_count) (sizeof(struct Driver_Template_Echo_Req) + DRIVER_TEMPLATE_ECHO_REQ_TAIL_ELEM_C_SIZE * (_tail_count))

/** Byte size of Driver_Template_Echo_Req in binary form (for a given tail length) */
#define DRIVER_TEMPLATE_ECHO_REQ_TAIL_ELEM_BIN_SIZE 1

/** Byte size of Driver_Template_Echo_Req in binary form (for a given tail length) */
#define DRIVER_TEMPLATE_ECHO_REQ_BIN_SIZE(_tail_elems) (1 + (_tail_elems) * DRIVER_TEMPLATE_ECHO_REQ_TAIL_ELEM_BIN_SIZE)

/** Payload Driver_Template_Echo_Req CSP destination address */
#define DRIVER_TEMPLATE_ECHO_REQ_DST_ADDR 1

/** Payload Driver_Template_Echo_Req CSP destination port */
#define DRIVER_TEMPLATE_ECHO_REQ_DST_PORT 2

/**
 * Payload "Echo_Rpl"
 *
 * Example echo reply
 */
struct Driver_Template_Echo_Rpl {
    uint16_t pld_id; //!< Payload ID
    size_t text_len; //!< Length of the "text"
    int8_t text[];
};

/* Associated constant values */

#define DRIVER_TEMPLATE_ECHO_RPL_CMD_ID 1

/** sizeof(Echo_Rpl) with a tail of given size */
#define DRIVER_TEMPLATE_ECHO_RPL_TAIL_ELEM_C_SIZE sizeof(((struct Driver_Template_Echo_Rpl*)0)->text[0])

/** sizeof(Echo_Rpl) with a tail of given size */
#define DRIVER_TEMPLATE_ECHO_RPL_C_SIZE(_tail_count) (sizeof(struct Driver_Template_Echo_Rpl) + DRIVER_TEMPLATE_ECHO_RPL_TAIL_ELEM_C_SIZE * (_tail_count))

/** Byte size of Driver_Template_Echo_Rpl in binary form (for a given tail length) */
#define DRIVER_TEMPLATE_ECHO_RPL_TAIL_ELEM_BIN_SIZE 1

/** Byte size of Driver_Template_Echo_Rpl in binary form (for a given tail length) */
#define DRIVER_TEMPLATE_ECHO_RPL_BIN_SIZE(_tail_elems) (1 + (_tail_elems) * DRIVER_TEMPLATE_ECHO_RPL_TAIL_ELEM_BIN_SIZE)

/** Payload Driver_Template_Echo_Rpl CSP source address */
#define DRIVER_TEMPLATE_ECHO_RPL_SRC_ADDR 1

/** Payload Driver_Template_Echo_Rpl CSP source port */
#define DRIVER_TEMPLATE_ECHO_RPL_SRC_PORT 2

/**
 * Payload "Kill"
 *
 * Kill request
 */
struct Driver_Template_Kill {
    uint16_t pld_id; //!< Payload ID
    /* empty */
};

/* Associated constant values */

#define DRIVER_TEMPLATE_KILL_CMD_ID 2

/** sizeof(Kill) */
#define DRIVER_TEMPLATE_KILL_C_SIZE (sizeof(struct Driver_Template_Kill))

/** Byte size of Driver_Template_Kill in binary form */
#define DRIVER_TEMPLATE_KILL_BIN_SIZE 1

/** Payload Driver_Template_Kill CSP destination address */
#define DRIVER_TEMPLATE_KILL_DST_ADDR 1

/** Payload Driver_Template_Kill CSP destination port */
#define DRIVER_TEMPLATE_KILL_DST_PORT 2

/** @}*/

/** @defgroup payloads_parsing Payload parsing
 *
 * Functions converting payload structs from their binary forms.
 *
 * All payload parsing functions share this signature:
 *
 * - <b>payload (in)</b> … a byte buffer to parse (e.g. received from CSP)
 * - <b>length (in)</b> … length of the payload buffer
 * - <b>alloc (in)</b> … allocator, malloc-like function used to allocate the output struct.
 *   The caller is responsible for disposing of the struct accordingly.
 * - <b>output (out)</b> … destination pointer, the parsed struct is output here
 *
 * The returned status code should be checked for errors.
 * @{
 */

#if PLD_HAVE_ALLOC
/** @brief Parse a binary payload into the "Ping" payload struct. */
pld_error_t Driver_Template_Ping_parse(const uint8_t *payload, size_t length, pld_alloc_fn alloc, struct Driver_Template_Ping **output);
#endif /* PLD_HAVE_ALLOC */

/** @brief Parse a binary payload into the "Ping" payload struct (static version) */
pld_error_t Driver_Template_Ping_parse_s(const uint8_t *payload, size_t length, struct Driver_Template_Ping *output);

#if PLD_HAVE_ALLOC
/** @brief Parse a binary payload into the "Pong" payload struct. */
pld_error_t Driver_Template_Pong_parse(const uint8_t *payload, size_t length, pld_alloc_fn alloc, struct Driver_Template_Pong **output);
#endif /* PLD_HAVE_ALLOC */

/** @brief Parse a binary payload into the "Pong" payload struct (static version) */
pld_error_t Driver_Template_Pong_parse_s(const uint8_t *payload, size_t length, struct Driver_Template_Pong *output);

#if PLD_HAVE_ALLOC
/** @brief Parse a binary payload into the "Echo_Req" payload struct. */
pld_error_t Driver_Template_Echo_Req_parse(const uint8_t *payload, size_t length, pld_alloc_fn alloc, struct Driver_Template_Echo_Req **output);
#endif /* PLD_HAVE_ALLOC */

/** @brief Parse a binary payload into the "Echo_Req" payload struct (static version) */
pld_error_t Driver_Template_Echo_Req_parse_s(const uint8_t *payload, size_t length, struct Driver_Template_Echo_Req *output);

#if PLD_HAVE_ALLOC
/** @brief Parse a binary payload into the "Echo_Rpl" payload struct. */
pld_error_t Driver_Template_Echo_Rpl_parse(const uint8_t *payload, size_t length, pld_alloc_fn alloc, struct Driver_Template_Echo_Rpl **output);
#endif /* PLD_HAVE_ALLOC */

/** @brief Parse a binary payload into the "Echo_Rpl" payload struct (static version) */
pld_error_t Driver_Template_Echo_Rpl_parse_s(const uint8_t *payload, size_t length, struct Driver_Template_Echo_Rpl *output);

#if PLD_HAVE_ALLOC
/** @brief Parse a binary payload into the "Kill" payload struct. */
pld_error_t Driver_Template_Kill_parse(const uint8_t *payload, size_t length, pld_alloc_fn alloc, struct Driver_Template_Kill **output);
#endif /* PLD_HAVE_ALLOC */

/** @brief Parse a binary payload into the "Kill" payload struct (static version) */
pld_error_t Driver_Template_Kill_parse_s(const uint8_t *payload, size_t length, struct Driver_Template_Kill *output);

/** @}*/

/** @defgroup payloads_building Payload building
 *
 * Functions converting payload structs into their binary forms.
 *
 * All payload building functions share this signature:
 *
 * - <b>data (in)</b> … the payload struct to read data from
 * - <b>alloc (in)</b> … allocator, malloc-like function called to obtain a byte buffer.
 *   The caller is responsible for disposing of the buffer accordingly.
 * - <b>output (out)</b> … destination pointer, the byte buffer is output here
 * - <b>len (out,optional)</b> … length of the output buffer is stored here (may be NULL if not needed)
 *
 * The returned status code should be checked for errors.
 * @{
 */

#if PLD_HAVE_ALLOC
/** @brief Encode payload struct "Ping" to its binary form. Data may be NULL. */
pld_error_t Driver_Template_Ping_build(const struct Driver_Template_Ping *data, pld_alloc_fn alloc, uint8_t **output, size_t *len);
#endif /* PLD_HAVE_ALLOC */

/** @brief Encode payload struct "Ping" to its binary form. Data may be NULL. (static version) */
pld_error_t Driver_Template_Ping_build_s(const struct Driver_Template_Ping *data, uint8_t *output, size_t capacity);

#if PLD_HAVE_ALLOC
/** @brief Encode payload struct "Pong" to its binary form. */
pld_error_t Driver_Template_Pong_build(const struct Driver_Template_Pong *data, pld_alloc_fn alloc, uint8_t **output, size_t *len);
#endif /* PLD_HAVE_ALLOC */

/** @brief Encode payload struct "Pong" to its binary form. (static version) */
pld_error_t Driver_Template_Pong_build_s(const struct Driver_Template_Pong *data, uint8_t *output, size_t capacity);

#if PLD_HAVE_ALLOC
/** @brief Encode payload struct "Echo_Req" to its binary form. */
pld_error_t Driver_Template_Echo_Req_build(const struct Driver_Template_Echo_Req *data, pld_alloc_fn alloc, uint8_t **output, size_t *len);
#endif /* PLD_HAVE_ALLOC */

/** @brief Encode payload struct "Echo_Req" to its binary form. (static version) */
pld_error_t Driver_Template_Echo_Req_build_s(const struct Driver_Template_Echo_Req *data, uint8_t *output, size_t capacity);

#if PLD_HAVE_ALLOC
/** @brief Encode payload struct "Echo_Rpl" to its binary form. */
pld_error_t Driver_Template_Echo_Rpl_build(const struct Driver_Template_Echo_Rpl *data, pld_alloc_fn alloc, uint8_t **output, size_t *len);
#endif /* PLD_HAVE_ALLOC */

/** @brief Encode payload struct "Echo_Rpl" to its binary form. (static version) */
pld_error_t Driver_Template_Echo_Rpl_build_s(const struct Driver_Template_Echo_Rpl *data, uint8_t *output, size_t capacity);

#if PLD_HAVE_ALLOC
/** @brief Encode payload struct "Kill" to its binary form. Data may be NULL. */
pld_error_t Driver_Template_Kill_build(const struct Driver_Template_Kill *data, pld_alloc_fn alloc, uint8_t **output, size_t *len);
#endif /* PLD_HAVE_ALLOC */

/** @brief Encode payload struct "Kill" to its binary form. Data may be NULL. (static version) */
pld_error_t Driver_Template_Kill_build_s(const struct Driver_Template_Kill *data, uint8_t *output, size_t capacity);

/** @}*/

#if PLD_HAVE_EXPORT
/** @defgroup payloads_building Payload building
 *
 * Functions converting payload structs into JSON.
 *
 * All payload export functions share this signature:
 *
 * - <b>data (in)</b> … the payload struct to read data from
 * - <b>style (in)</b> … JSON variant (EXPORT_JSON_DATAONLY, EXPORT_JSON_ANNOTATED)
 * - <b>output (out)</b> … destination pointer, the json is output here
 *
 * The returned status code should be checked for errors.
 * @{
 */

/** @brief Export payload struct "Ping" to JSON (without look-up) */
pld_error_t Driver_Template_Ping_to_json(const struct Driver_Template_Ping *data, enum pld_export_json_style style, cJSON** output);

/** @brief Export payload struct "Pong" to JSON (without look-up) */
pld_error_t Driver_Template_Pong_to_json(const struct Driver_Template_Pong *data, enum pld_export_json_style style, cJSON** output);

/** @brief Export payload struct "Echo_Req" to JSON (without look-up) */
pld_error_t Driver_Template_Echo_Req_to_json(const struct Driver_Template_Echo_Req *data, enum pld_export_json_style style, cJSON** output);

/** @brief Export payload struct "Echo_Rpl" to JSON (without look-up) */
pld_error_t Driver_Template_Echo_Rpl_to_json(const struct Driver_Template_Echo_Rpl *data, enum pld_export_json_style style, cJSON** output);

/** @brief Export payload struct "Kill" to JSON (without look-up) */
pld_error_t Driver_Template_Kill_to_json(const struct Driver_Template_Kill *data, enum pld_export_json_style style, cJSON** output);

/** @}*/
#endif /* PLD_HAVE_EXPORT */

#endif /* PLD_DRIVER_TEMPLATE_H */
