option('csp_platform', type : 'combo', value : 'posix', choices : ['freertos', 'posix', 'windows', 'macosx', 'stm32h7'], description : 'Platform')
option('csp_i2c_frame_packed', type : 'boolean', value : false, description : 'Make the I2C frame packed')
option('csp_debug', type : 'boolean', value : true, description : 'Debug logging enabled')
option('csp_use_external_debug', type : 'boolean', value : false, description : 'Do not use the bundled csp_debug.c')
option('csp_use_custom_printf', type : 'boolean', value : false, description : 'Use external csp_printf implementations instead of stdlib')
option('csp_log_level', type : 'combo', value : 'debug', choices : ['debug', 'info', 'warn', 'error'], description : 'Log level')
option('csp_use_rdp', type : 'boolean', value : true, description : 'Support RDP')
option('csp_use_rdp_fast_close', type : 'boolean', value : true, description : 'Use RDP fast close mode (if RDP used)')
option('csp_use_crc32', type : 'boolean', value : true, description : 'Support CRC32')
option('csp_use_hmac', type : 'boolean', value : true, description : 'Support HMAC')
option('csp_use_xtea', type : 'boolean', value : true, description : 'Support XTEA')
option('csp_use_promisc', type : 'boolean', value : true, description : 'Support promiscuous mode')
option('csp_use_qos', type : 'boolean', value : true, description : 'Support QoS')
option('csp_use_dedup', type : 'boolean', value : false, description : 'Use deduplication')
option('csp_use_cidr_rtable', type : 'boolean', value : true, description : 'Use CIDR routing table (false = static)')
option('csp_use_ifc_i2c', type : 'boolean', value : true, description : 'uSe I2C interface')
option('csp_use_ifc_kiss', type : 'boolean', value : false, description : 'use KISS interface')
option('csp_usart_windows', type : 'boolean', value : false, description : 'Use Windows USART driver')
option('csp_usart_linux', type : 'boolean', value : false, description : 'uSe Linux USART driver')
option('csp_use_ifc_can', type : 'boolean', value : false, description : 'uSe CAN interface')
option('csp_can_socketcan', type : 'boolean', value : false, description : 'Use the built-in socketcan driver')
option('csp_have_libsocketcan', type : 'boolean', value : false, description : 'Use socketcan library')
option('csp_have_sscanf', type : 'boolean', value : true, description : 'Use sscanf for routing table parsing')
option('csp_have_rand', type : 'boolean', value : true, description : 'Use rand(). Disable to use a custom PRNG')
option('enable_python3_bindings', type: 'boolean', value: false, description: 'Build Python 3 binding')

