/**
 * Payload specs module LTC
 *
 * Generated by lpldgen 1.4.6
 */

#include "pld_ltc.h"
#include <payloads_internal.h>

#if PLD_HAVE_ALLOC
pld_error_t LTC_SET_MODE_REQ_parse(const uint8_t * bytes, const size_t length, pld_alloc_fn alloc, struct LTC_SET_MODE_REQ **output) {
    pld_log_trace("LTC_SET_MODE_REQ_parse");
    if (length != LTC_SET_MODE_REQ_BIN_SIZE) return PLD_ERR_LENGTH;
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    struct LTC_SET_MODE_REQ *data = alloc(LTC_SET_MODE_REQ_C_SIZE);
    if (NULL == data) {
        pld_log_error("payload struct alloc failed");
        return PLD_ERR_ALLOC;
    }
    *output = data;
    
    return LTC_SET_MODE_REQ_parse_s(bytes, length, data);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t LTC_SET_MODE_REQ_parse_s(const uint8_t * bytes, const size_t length, struct LTC_SET_MODE_REQ *output) {
    pld_log_trace("LTC_SET_MODE_REQ_parse_s");
    uint32_t tmp32 = 0;
    if (length != LTC_SET_MODE_REQ_BIN_SIZE) return PLD_ERR_LENGTH;
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!bytes) {
        pld_log_error("buffer is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    output->pld_id = LTC_SET_MODE_REQ_ID;
    
    /* parsing */
    bytes++;
    
    output->mode = (uint8_t)(*bytes++);
    
    output->set_frequency = (uint8_t)(*bytes++);
    
    tmp32 = 0;
    tmp32 |= (uint32_t) *bytes++ << 24;
    tmp32 |= (uint32_t) *bytes++ << 16;
    tmp32 |= (uint32_t) *bytes++ << 8;
    tmp32 |= (uint32_t) *bytes;
    output->frequency = (uint32_t)(tmp32);
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t LTC_SET_MODE_RSP_parse(const uint8_t * bytes, const size_t length, pld_alloc_fn alloc, struct LTC_SET_MODE_RSP **output) {
    pld_log_trace("LTC_SET_MODE_RSP_parse");
    if (length != LTC_SET_MODE_RSP_BIN_SIZE) return PLD_ERR_LENGTH;
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    struct LTC_SET_MODE_RSP *data = alloc(LTC_SET_MODE_RSP_C_SIZE);
    if (NULL == data) {
        pld_log_error("payload struct alloc failed");
        return PLD_ERR_ALLOC;
    }
    *output = data;
    
    return LTC_SET_MODE_RSP_parse_s(bytes, length, data);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t LTC_SET_MODE_RSP_parse_s(const uint8_t * bytes, const size_t length, struct LTC_SET_MODE_RSP *output) {
    pld_log_trace("LTC_SET_MODE_RSP_parse_s");
    uint8_t i = 0;
    if (length != LTC_SET_MODE_RSP_BIN_SIZE) return PLD_ERR_LENGTH;
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!bytes) {
        pld_log_error("buffer is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    output->pld_id = LTC_SET_MODE_RSP_ID;
    
    /* parsing */
    bytes++;
    
    output->status = (uint8_t)(*bytes++);
    
    for (i = 0; i < 25; i++) {
        output->error[i] = ((x8_t){ .u=(int8_t)(*bytes++) }).i;
    }
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t LTC_GET_STATUS_REQ_parse(const uint8_t * bytes, const size_t length, pld_alloc_fn alloc, struct LTC_GET_STATUS_REQ **output) {
    pld_log_trace("LTC_GET_STATUS_REQ_parse");
    if (length != LTC_GET_STATUS_REQ_BIN_SIZE) return PLD_ERR_LENGTH;
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    struct LTC_GET_STATUS_REQ *data = alloc(LTC_GET_STATUS_REQ_C_SIZE);
    if (NULL == data) {
        pld_log_error("payload struct alloc failed");
        return PLD_ERR_ALLOC;
    }
    *output = data;
    
    return LTC_GET_STATUS_REQ_parse_s(bytes, length, data);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t LTC_GET_STATUS_REQ_parse_s(const uint8_t * bytes, const size_t length, struct LTC_GET_STATUS_REQ *output) {
    pld_log_trace("LTC_GET_STATUS_REQ_parse_s");
    if (length != LTC_GET_STATUS_REQ_BIN_SIZE) return PLD_ERR_LENGTH;
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!bytes) {
        pld_log_error("buffer is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    output->pld_id = LTC_GET_STATUS_REQ_ID;
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t LTC_GET_STATUS_RSP_parse(const uint8_t * bytes, const size_t length, pld_alloc_fn alloc, struct LTC_GET_STATUS_RSP **output) {
    pld_log_trace("LTC_GET_STATUS_RSP_parse");
    if (length != LTC_GET_STATUS_RSP_BIN_SIZE) return PLD_ERR_LENGTH;
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    struct LTC_GET_STATUS_RSP *data = alloc(LTC_GET_STATUS_RSP_C_SIZE);
    if (NULL == data) {
        pld_log_error("payload struct alloc failed");
        return PLD_ERR_ALLOC;
    }
    *output = data;
    
    return LTC_GET_STATUS_RSP_parse_s(bytes, length, data);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t LTC_GET_STATUS_RSP_parse_s(const uint8_t * bytes, const size_t length, struct LTC_GET_STATUS_RSP *output) {
    pld_log_trace("LTC_GET_STATUS_RSP_parse_s");
    uint32_t tmp32 = 0;
    if (length != LTC_GET_STATUS_RSP_BIN_SIZE) return PLD_ERR_LENGTH;
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!bytes) {
        pld_log_error("buffer is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    output->pld_id = LTC_GET_STATUS_RSP_ID;
    
    /* parsing */
    bytes++;
    
    output->mode = (uint8_t)(*bytes++);
    
    output->result_status = (uint8_t)(*bytes++);
    
    tmp32 = 0;
    tmp32 |= (uint32_t) *bytes++ << 24;
    tmp32 |= (uint32_t) *bytes++ << 16;
    tmp32 |= (uint32_t) *bytes++ << 8;
    tmp32 |= (uint32_t) *bytes++;
    output->frequency = (uint32_t)(tmp32);
    
    output->error = (uint8_t)(*bytes);
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t LTC_READ_TEMP_REQ_parse(const uint8_t * bytes, const size_t length, pld_alloc_fn alloc, struct LTC_READ_TEMP_REQ **output) {
    pld_log_trace("LTC_READ_TEMP_REQ_parse");
    if (length != LTC_READ_TEMP_REQ_BIN_SIZE) return PLD_ERR_LENGTH;
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    struct LTC_READ_TEMP_REQ *data = alloc(LTC_READ_TEMP_REQ_C_SIZE);
    if (NULL == data) {
        pld_log_error("payload struct alloc failed");
        return PLD_ERR_ALLOC;
    }
    *output = data;
    
    return LTC_READ_TEMP_REQ_parse_s(bytes, length, data);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t LTC_READ_TEMP_REQ_parse_s(const uint8_t * bytes, const size_t length, struct LTC_READ_TEMP_REQ *output) {
    pld_log_trace("LTC_READ_TEMP_REQ_parse_s");
    if (length != LTC_READ_TEMP_REQ_BIN_SIZE) return PLD_ERR_LENGTH;
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!bytes) {
        pld_log_error("buffer is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    output->pld_id = LTC_READ_TEMP_REQ_ID;
    
    /* parsing */
    bytes++;
    
    output->channel_id = (uint8_t)(*bytes++);
    
    output->force_measurement = (uint8_t)(*bytes);
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t LTC_READ_TEMP_RSP_parse(const uint8_t * bytes, const size_t length, pld_alloc_fn alloc, struct LTC_READ_TEMP_RSP **output) {
    pld_log_trace("LTC_READ_TEMP_RSP_parse");
    if (length != LTC_READ_TEMP_RSP_BIN_SIZE) return PLD_ERR_LENGTH;
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    struct LTC_READ_TEMP_RSP *data = alloc(LTC_READ_TEMP_RSP_C_SIZE);
    if (NULL == data) {
        pld_log_error("payload struct alloc failed");
        return PLD_ERR_ALLOC;
    }
    *output = data;
    
    return LTC_READ_TEMP_RSP_parse_s(bytes, length, data);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t LTC_READ_TEMP_RSP_parse_s(const uint8_t * bytes, const size_t length, struct LTC_READ_TEMP_RSP *output) {
    pld_log_trace("LTC_READ_TEMP_RSP_parse_s");
    uint32_t tmp32 = 0;
    uint8_t i = 0;
    if (length != LTC_READ_TEMP_RSP_BIN_SIZE) return PLD_ERR_LENGTH;
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!bytes) {
        pld_log_error("buffer is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    output->pld_id = LTC_READ_TEMP_RSP_ID;
    
    /* parsing */
    bytes++;
    
    output->result_ready = (uint8_t)(*bytes++);
    
    for (i = 0; i < 20; i++) {
        output->TempRslt[i].channel = (uint8_t)(*bytes++);
        output->TempRslt[i].status = (uint8_t)(*bytes++);
        tmp32 = 0;
        tmp32 |= (uint32_t) *bytes++ << 24;
        tmp32 |= (uint32_t) *bytes++ << 16;
        tmp32 |= (uint32_t) *bytes++ << 8;
        tmp32 |= (uint32_t) *bytes++;
        output->TempRslt[i].temperature = ((x32_t){ .u=(tmp32) }).f;
        tmp32 = 0;
        tmp32 |= (uint32_t) *bytes++ << 24;
        tmp32 |= (uint32_t) *bytes++ << 16;
        tmp32 |= (uint32_t) *bytes++ << 8;
        tmp32 |= (uint32_t) *bytes++;
        output->TempRslt[i].raw = ((x32_t){ .u=(tmp32) }).f;
    }
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t LTC_SET_RSENSE_REQ_parse(const uint8_t * bytes, const size_t length, pld_alloc_fn alloc, struct LTC_SET_RSENSE_REQ **output) {
    pld_log_trace("LTC_SET_RSENSE_REQ_parse");
    if (length != LTC_SET_RSENSE_REQ_BIN_SIZE) return PLD_ERR_LENGTH;
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    struct LTC_SET_RSENSE_REQ *data = alloc(LTC_SET_RSENSE_REQ_C_SIZE);
    if (NULL == data) {
        pld_log_error("payload struct alloc failed");
        return PLD_ERR_ALLOC;
    }
    *output = data;
    
    return LTC_SET_RSENSE_REQ_parse_s(bytes, length, data);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t LTC_SET_RSENSE_REQ_parse_s(const uint8_t * bytes, const size_t length, struct LTC_SET_RSENSE_REQ *output) {
    pld_log_trace("LTC_SET_RSENSE_REQ_parse_s");
    uint32_t tmp32 = 0;
    if (length != LTC_SET_RSENSE_REQ_BIN_SIZE) return PLD_ERR_LENGTH;
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!bytes) {
        pld_log_error("buffer is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    output->pld_id = LTC_SET_RSENSE_REQ_ID;
    
    /* parsing */
    bytes++;
    
    tmp32 = 0;
    tmp32 |= (uint32_t) *bytes++ << 24;
    tmp32 |= (uint32_t) *bytes++ << 16;
    tmp32 |= (uint32_t) *bytes++ << 8;
    tmp32 |= (uint32_t) *bytes;
    output->val = ((x32_t){ .u=(tmp32) }).f;
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t LTC_SET_RSENSE_RSP_parse(const uint8_t * bytes, const size_t length, pld_alloc_fn alloc, struct LTC_SET_RSENSE_RSP **output) {
    pld_log_trace("LTC_SET_RSENSE_RSP_parse");
    if (length != LTC_SET_RSENSE_RSP_BIN_SIZE) return PLD_ERR_LENGTH;
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    struct LTC_SET_RSENSE_RSP *data = alloc(LTC_SET_RSENSE_RSP_C_SIZE);
    if (NULL == data) {
        pld_log_error("payload struct alloc failed");
        return PLD_ERR_ALLOC;
    }
    *output = data;
    
    return LTC_SET_RSENSE_RSP_parse_s(bytes, length, data);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t LTC_SET_RSENSE_RSP_parse_s(const uint8_t * bytes, const size_t length, struct LTC_SET_RSENSE_RSP *output) {
    pld_log_trace("LTC_SET_RSENSE_RSP_parse_s");
    if (length != LTC_SET_RSENSE_RSP_BIN_SIZE) return PLD_ERR_LENGTH;
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!bytes) {
        pld_log_error("buffer is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    output->pld_id = LTC_SET_RSENSE_RSP_ID;
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t LTC_SET_MODE_REQ_build(const struct LTC_SET_MODE_REQ * const data, pld_alloc_fn alloc, uint8_t **output, size_t *len) {
    pld_log_trace("LTC_SET_MODE_REQ_build");
    const size_t byte_size = LTC_SET_MODE_REQ_BIN_SIZE;
    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!len) {
        pld_log_error("len is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != LTC_SET_MODE_REQ_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, LTC_SET_MODE_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != LTC_SET_MODE_REQ_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, LTC_SET_MODE_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    uint8_t *pld = alloc(byte_size);
    if (NULL == pld) {
        pld_log_error("payload buffer alloc failed");
        return PLD_ERR_ALLOC;
    }
    
    *output = pld;
    *len = byte_size;
    
    return LTC_SET_MODE_REQ_build_s(data, pld, byte_size);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t LTC_SET_MODE_REQ_build_s(const struct LTC_SET_MODE_REQ * const data, uint8_t *output, size_t capacity) {
    pld_log_trace("LTC_SET_MODE_REQ_build_s");
    uint32_t tmp32 = 0;
    const size_t byte_size = LTC_SET_MODE_REQ_BIN_SIZE;
    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != LTC_SET_MODE_REQ_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, LTC_SET_MODE_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != LTC_SET_MODE_REQ_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, LTC_SET_MODE_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    if (capacity < byte_size) {
        pld_log_error("insufficient buffer capacity (%d, need %d)", (int)capacity, (int)byte_size);
        return PLD_ERR_LENGTH;
    }
    
    *output++ = 0x00;
    
    *output++ = (uint8_t)(data->mode);
    
    *output++ = (uint8_t)(data->set_frequency);
    
    tmp32 = (uint32_t)(data->frequency);
    *output++ = (uint8_t) ((tmp32 >> 24) & 0xff);
    *output++ = (uint8_t) ((tmp32 >> 16) & 0xff);
    *output++ = (uint8_t) ((tmp32 >> 8) & 0xff);
    *output++ = (uint8_t) (tmp32 & 0xff);
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t LTC_SET_MODE_RSP_build(const struct LTC_SET_MODE_RSP * const data, pld_alloc_fn alloc, uint8_t **output, size_t *len) {
    pld_log_trace("LTC_SET_MODE_RSP_build");
    const size_t byte_size = LTC_SET_MODE_RSP_BIN_SIZE;
    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!len) {
        pld_log_error("len is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != LTC_SET_MODE_RSP_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, LTC_SET_MODE_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != LTC_SET_MODE_RSP_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, LTC_SET_MODE_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    uint8_t *pld = alloc(byte_size);
    if (NULL == pld) {
        pld_log_error("payload buffer alloc failed");
        return PLD_ERR_ALLOC;
    }
    
    *output = pld;
    *len = byte_size;
    
    return LTC_SET_MODE_RSP_build_s(data, pld, byte_size);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t LTC_SET_MODE_RSP_build_s(const struct LTC_SET_MODE_RSP * const data, uint8_t *output, size_t capacity) {
    pld_log_trace("LTC_SET_MODE_RSP_build_s");
    uint8_t i = 0;
    const size_t byte_size = LTC_SET_MODE_RSP_BIN_SIZE;
    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != LTC_SET_MODE_RSP_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, LTC_SET_MODE_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != LTC_SET_MODE_RSP_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, LTC_SET_MODE_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    if (capacity < byte_size) {
        pld_log_error("insufficient buffer capacity (%d, need %d)", (int)capacity, (int)byte_size);
        return PLD_ERR_LENGTH;
    }
    
    *output++ = 0x00;
    
    *output++ = (uint8_t)(data->status);
    
    for (i = 0; i < 25; i++) {
        *output++ = ((x8_t){ .i=(int8_t)(data->error[i]) }).u;
    }
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t LTC_GET_STATUS_REQ_build(const struct LTC_GET_STATUS_REQ * const data, pld_alloc_fn alloc, uint8_t **output, size_t *len) {
    pld_log_trace("LTC_GET_STATUS_REQ_build");
    const size_t byte_size = LTC_GET_STATUS_REQ_BIN_SIZE;
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!len) {
        pld_log_error("len is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != LTC_GET_STATUS_REQ_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, LTC_GET_STATUS_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != LTC_GET_STATUS_REQ_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, LTC_GET_STATUS_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    uint8_t *pld = alloc(byte_size);
    if (NULL == pld) {
        pld_log_error("payload buffer alloc failed");
        return PLD_ERR_ALLOC;
    }
    
    *output = pld;
    *len = byte_size;
    
    return LTC_GET_STATUS_REQ_build_s(data, pld, byte_size);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t LTC_GET_STATUS_REQ_build_s(const struct LTC_GET_STATUS_REQ * const data, uint8_t *output, size_t capacity) {
    pld_log_trace("LTC_GET_STATUS_REQ_build_s");
    const size_t byte_size = LTC_GET_STATUS_REQ_BIN_SIZE;
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != LTC_GET_STATUS_REQ_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, LTC_GET_STATUS_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != LTC_GET_STATUS_REQ_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, LTC_GET_STATUS_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    if (capacity < byte_size) {
        pld_log_error("insufficient buffer capacity (%d, need %d)", (int)capacity, (int)byte_size);
        return PLD_ERR_LENGTH;
    }
    
    *output++ = 0x01;
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t LTC_GET_STATUS_RSP_build(const struct LTC_GET_STATUS_RSP * const data, pld_alloc_fn alloc, uint8_t **output, size_t *len) {
    pld_log_trace("LTC_GET_STATUS_RSP_build");
    const size_t byte_size = LTC_GET_STATUS_RSP_BIN_SIZE;
    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!len) {
        pld_log_error("len is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != LTC_GET_STATUS_RSP_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, LTC_GET_STATUS_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != LTC_GET_STATUS_RSP_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, LTC_GET_STATUS_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    uint8_t *pld = alloc(byte_size);
    if (NULL == pld) {
        pld_log_error("payload buffer alloc failed");
        return PLD_ERR_ALLOC;
    }
    
    *output = pld;
    *len = byte_size;
    
    return LTC_GET_STATUS_RSP_build_s(data, pld, byte_size);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t LTC_GET_STATUS_RSP_build_s(const struct LTC_GET_STATUS_RSP * const data, uint8_t *output, size_t capacity) {
    pld_log_trace("LTC_GET_STATUS_RSP_build_s");
    uint32_t tmp32 = 0;
    const size_t byte_size = LTC_GET_STATUS_RSP_BIN_SIZE;
    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != LTC_GET_STATUS_RSP_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, LTC_GET_STATUS_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != LTC_GET_STATUS_RSP_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, LTC_GET_STATUS_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    if (capacity < byte_size) {
        pld_log_error("insufficient buffer capacity (%d, need %d)", (int)capacity, (int)byte_size);
        return PLD_ERR_LENGTH;
    }
    
    *output++ = 0x01;
    
    *output++ = (uint8_t)(data->mode);
    
    *output++ = (uint8_t)(data->result_status);
    
    tmp32 = (uint32_t)(data->frequency);
    *output++ = (uint8_t) ((tmp32 >> 24) & 0xff);
    *output++ = (uint8_t) ((tmp32 >> 16) & 0xff);
    *output++ = (uint8_t) ((tmp32 >> 8) & 0xff);
    *output++ = (uint8_t) (tmp32 & 0xff);
    
    *output++ = (uint8_t)(data->error);
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t LTC_READ_TEMP_REQ_build(const struct LTC_READ_TEMP_REQ * const data, pld_alloc_fn alloc, uint8_t **output, size_t *len) {
    pld_log_trace("LTC_READ_TEMP_REQ_build");
    const size_t byte_size = LTC_READ_TEMP_REQ_BIN_SIZE;
    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!len) {
        pld_log_error("len is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != LTC_READ_TEMP_REQ_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, LTC_READ_TEMP_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != LTC_READ_TEMP_REQ_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, LTC_READ_TEMP_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    uint8_t *pld = alloc(byte_size);
    if (NULL == pld) {
        pld_log_error("payload buffer alloc failed");
        return PLD_ERR_ALLOC;
    }
    
    *output = pld;
    *len = byte_size;
    
    return LTC_READ_TEMP_REQ_build_s(data, pld, byte_size);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t LTC_READ_TEMP_REQ_build_s(const struct LTC_READ_TEMP_REQ * const data, uint8_t *output, size_t capacity) {
    pld_log_trace("LTC_READ_TEMP_REQ_build_s");
    const size_t byte_size = LTC_READ_TEMP_REQ_BIN_SIZE;
    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != LTC_READ_TEMP_REQ_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, LTC_READ_TEMP_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != LTC_READ_TEMP_REQ_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, LTC_READ_TEMP_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    if (capacity < byte_size) {
        pld_log_error("insufficient buffer capacity (%d, need %d)", (int)capacity, (int)byte_size);
        return PLD_ERR_LENGTH;
    }
    
    *output++ = 0x02;
    
    *output++ = (uint8_t)(data->channel_id);
    
    *output++ = (uint8_t)(data->force_measurement);
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t LTC_READ_TEMP_RSP_build(const struct LTC_READ_TEMP_RSP * const data, pld_alloc_fn alloc, uint8_t **output, size_t *len) {
    pld_log_trace("LTC_READ_TEMP_RSP_build");
    const size_t byte_size = LTC_READ_TEMP_RSP_BIN_SIZE;
    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!len) {
        pld_log_error("len is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != LTC_READ_TEMP_RSP_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, LTC_READ_TEMP_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != LTC_READ_TEMP_RSP_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, LTC_READ_TEMP_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    uint8_t *pld = alloc(byte_size);
    if (NULL == pld) {
        pld_log_error("payload buffer alloc failed");
        return PLD_ERR_ALLOC;
    }
    
    *output = pld;
    *len = byte_size;
    
    return LTC_READ_TEMP_RSP_build_s(data, pld, byte_size);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t LTC_READ_TEMP_RSP_build_s(const struct LTC_READ_TEMP_RSP * const data, uint8_t *output, size_t capacity) {
    pld_log_trace("LTC_READ_TEMP_RSP_build_s");
    uint32_t tmp32 = 0;
    uint8_t i = 0;
    const size_t byte_size = LTC_READ_TEMP_RSP_BIN_SIZE;
    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != LTC_READ_TEMP_RSP_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, LTC_READ_TEMP_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != LTC_READ_TEMP_RSP_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, LTC_READ_TEMP_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    if (capacity < byte_size) {
        pld_log_error("insufficient buffer capacity (%d, need %d)", (int)capacity, (int)byte_size);
        return PLD_ERR_LENGTH;
    }
    
    *output++ = 0x02;
    
    *output++ = (uint8_t)(data->result_ready);
    
    for (i = 0; i < 20; i++) {
        *output++ = (uint8_t)(data->TempRslt[i].channel);
        *output++ = (uint8_t)(data->TempRslt[i].status);
        tmp32 = ((x32_t){ .f=(data->TempRslt[i].temperature) }).u;
        *output++ = (uint8_t) ((tmp32 >> 24) & 0xff);
        *output++ = (uint8_t) ((tmp32 >> 16) & 0xff);
        *output++ = (uint8_t) ((tmp32 >> 8) & 0xff);
        *output++ = (uint8_t) (tmp32 & 0xff);
        tmp32 = ((x32_t){ .f=(data->TempRslt[i].raw) }).u;
        *output++ = (uint8_t) ((tmp32 >> 24) & 0xff);
        *output++ = (uint8_t) ((tmp32 >> 16) & 0xff);
        *output++ = (uint8_t) ((tmp32 >> 8) & 0xff);
        *output++ = (uint8_t) (tmp32 & 0xff);
    }
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t LTC_SET_RSENSE_REQ_build(const struct LTC_SET_RSENSE_REQ * const data, pld_alloc_fn alloc, uint8_t **output, size_t *len) {
    pld_log_trace("LTC_SET_RSENSE_REQ_build");
    const size_t byte_size = LTC_SET_RSENSE_REQ_BIN_SIZE;
    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!len) {
        pld_log_error("len is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != LTC_SET_RSENSE_REQ_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, LTC_SET_RSENSE_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != LTC_SET_RSENSE_REQ_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, LTC_SET_RSENSE_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    uint8_t *pld = alloc(byte_size);
    if (NULL == pld) {
        pld_log_error("payload buffer alloc failed");
        return PLD_ERR_ALLOC;
    }
    
    *output = pld;
    *len = byte_size;
    
    return LTC_SET_RSENSE_REQ_build_s(data, pld, byte_size);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t LTC_SET_RSENSE_REQ_build_s(const struct LTC_SET_RSENSE_REQ * const data, uint8_t *output, size_t capacity) {
    pld_log_trace("LTC_SET_RSENSE_REQ_build_s");
    uint32_t tmp32 = 0;
    const size_t byte_size = LTC_SET_RSENSE_REQ_BIN_SIZE;
    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != LTC_SET_RSENSE_REQ_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, LTC_SET_RSENSE_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != LTC_SET_RSENSE_REQ_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, LTC_SET_RSENSE_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    if (capacity < byte_size) {
        pld_log_error("insufficient buffer capacity (%d, need %d)", (int)capacity, (int)byte_size);
        return PLD_ERR_LENGTH;
    }
    
    *output++ = 0x03;
    
    tmp32 = ((x32_t){ .f=(data->val) }).u;
    *output++ = (uint8_t) ((tmp32 >> 24) & 0xff);
    *output++ = (uint8_t) ((tmp32 >> 16) & 0xff);
    *output++ = (uint8_t) ((tmp32 >> 8) & 0xff);
    *output++ = (uint8_t) (tmp32 & 0xff);
    
    return PLD_OK;
}

#if PLD_HAVE_ALLOC
pld_error_t LTC_SET_RSENSE_RSP_build(const struct LTC_SET_RSENSE_RSP * const data, pld_alloc_fn alloc, uint8_t **output, size_t *len) {
    pld_log_trace("LTC_SET_RSENSE_RSP_build");
    const size_t byte_size = LTC_SET_RSENSE_RSP_BIN_SIZE;
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    if (!len) {
        pld_log_error("len is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != LTC_SET_RSENSE_RSP_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, LTC_SET_RSENSE_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != LTC_SET_RSENSE_RSP_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, LTC_SET_RSENSE_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    uint8_t *pld = alloc(byte_size);
    if (NULL == pld) {
        pld_log_error("payload buffer alloc failed");
        return PLD_ERR_ALLOC;
    }
    
    *output = pld;
    *len = byte_size;
    
    return LTC_SET_RSENSE_RSP_build_s(data, pld, byte_size);
}
#endif /* PLD_HAVE_ALLOC */

pld_error_t LTC_SET_RSENSE_RSP_build_s(const struct LTC_SET_RSENSE_RSP * const data, uint8_t *output, size_t capacity) {
    pld_log_trace("LTC_SET_RSENSE_RSP_build_s");
    const size_t byte_size = LTC_SET_RSENSE_RSP_BIN_SIZE;
    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }
    
    #if PLD_BUILD_FUNCS_CHECK_ID == 1
        if (data && data->pld_id != LTC_SET_RSENSE_RSP_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, LTC_SET_RSENSE_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #elif PLD_BUILD_FUNCS_CHECK_ID == 2
        if (data && data->pld_id != PAYLOAD_ID_NONE && data->pld_id != LTC_SET_RSENSE_RSP_ID) {
            pld_log_error("payload ID %d set and does not match expected %d", data->pld_id, LTC_SET_RSENSE_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif
    
    if (capacity < byte_size) {
        pld_log_error("insufficient buffer capacity (%d, need %d)", (int)capacity, (int)byte_size);
        return PLD_ERR_LENGTH;
    }
    
    *output++ = 0x03;
    
    return PLD_OK;
}

/** Test constants in a "SET_MODE_REQ" payload */
static bool LTC_SET_MODE_REQ_test(const uint8_t * const bytes) {
    return (bytes[0] == 0x00);
}

/** Test constants in a "SET_MODE_RSP" payload */
static bool LTC_SET_MODE_RSP_test(const uint8_t * const bytes) {
    return (bytes[0] == 0x00);
}

/** Test constants in a "GET_STATUS_REQ" payload */
static bool LTC_GET_STATUS_REQ_test(const uint8_t * const bytes) {
    return (bytes[0] == 0x01);
}

/** Test constants in a "GET_STATUS_RSP" payload */
static bool LTC_GET_STATUS_RSP_test(const uint8_t * const bytes) {
    return (bytes[0] == 0x01);
}

/** Test constants in a "READ_TEMP_REQ" payload */
static bool LTC_READ_TEMP_REQ_test(const uint8_t * const bytes) {
    return (bytes[0] == 0x02);
}

/** Test constants in a "READ_TEMP_RSP" payload */
static bool LTC_READ_TEMP_RSP_test(const uint8_t * const bytes) {
    return (bytes[0] == 0x02);
}

/** Test constants in a "SET_RSENSE_REQ" payload */
static bool LTC_SET_RSENSE_REQ_test(const uint8_t * const bytes) {
    return (bytes[0] == 0x03);
}

/** Test constants in a "SET_RSENSE_RSP" payload */
static bool LTC_SET_RSENSE_RSP_test(const uint8_t * const bytes) {
    return (bytes[0] == 0x03);
}

#if PLD_HAVE_EXPORT
#include <inttypes.h>

static pld_error_t LTC_SET_MODE_REQ_to_json_inner(const struct LTC_SET_MODE_REQ *data, enum pld_export_json_style style, cJSON* output) {
    pld_log_trace("LTC_SET_MODE_REQ_to_json_inner");

    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    #if PLD_EXPORT_FUNCS_CHECK_ID
        if (data->pld_id != LTC_SET_MODE_REQ_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, LTC_SET_MODE_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif

    cJSON *item0 = NULL;
    cJSON *item1 = NULL;
    cJSON *item2 = NULL;
    

    // suppress unused warnings
    (void)data;
    (void)output;

    switch (style) {
        case EXPORT_JSON_DATAONLY:
            pld_log_trace("export as data-only");
            CJSON_TRY(item0 = cJSON_CreateNumber(data->mode));
            cJSON_AddItemToObjectCS(output, "mode", item0);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->set_frequency));
            cJSON_AddItemToObjectCS(output, "set_frequency", item0);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->frequency));
            cJSON_AddItemToObjectCS(output, "frequency", item0);
            break;
        case EXPORT_JSON_ANNOTATED:
            pld_log_trace("export annotated");
            CJSON_TRY(item1 = cJSON_CreateObject());
            cJSON_AddItemToObjectCS(output, "mode", item1);
            CJSON_TRY(item2 = cJSON_CreateStringReference("Set flags for reading temps"));
            cJSON_AddItemToObjectCS(item1, "descr", item2);
            CJSON_TRY(item2 = cJSON_CreateStringReference("u8"));
            cJSON_AddItemToObjectCS(item1, "type", item2);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->mode));
            cJSON_AddItemToObjectCS(item1, "value", item0);
            CJSON_TRY(item1 = cJSON_CreateObject());
            cJSON_AddItemToObjectCS(output, "set_frequency", item1);
            CJSON_TRY(item2 = cJSON_CreateStringReference("A flag to know if you are sending a frequency too"));
            cJSON_AddItemToObjectCS(item1, "descr", item2);
            CJSON_TRY(item2 = cJSON_CreateStringReference("u8"));
            cJSON_AddItemToObjectCS(item1, "type", item2);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->set_frequency));
            cJSON_AddItemToObjectCS(item1, "value", item0);
            CJSON_TRY(item1 = cJSON_CreateObject());
            cJSON_AddItemToObjectCS(output, "frequency", item1);
            CJSON_TRY(item2 = cJSON_CreateStringReference("Continuous measurement frequency"));
            cJSON_AddItemToObjectCS(item1, "descr", item2);
            CJSON_TRY(item2 = cJSON_CreateStringReference("u32"));
            cJSON_AddItemToObjectCS(item1, "type", item2);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->frequency));
            cJSON_AddItemToObjectCS(item1, "value", item0);
            break;
        default:
            pld_log_error("bad export style");
            return PLD_ERR_NOT_IMPLEMENTED;
    }
    return PLD_OK;
cjfail:
    return PLD_ERR_ALLOC; /* will be deallocated by caller */
}

pld_error_t LTC_SET_MODE_REQ_to_json(const struct LTC_SET_MODE_REQ *data, enum pld_export_json_style style, cJSON** output) {
    pld_log_trace("LTC_SET_MODE_REQ_to_json");
    return pld_to_json_by_spec(PldSpec_LTC_SET_MODE_REQ, data, style, output);
}

static pld_error_t LTC_SET_MODE_RSP_to_json_inner(const struct LTC_SET_MODE_RSP *data, enum pld_export_json_style style, cJSON* output) {
    pld_log_trace("LTC_SET_MODE_RSP_to_json_inner");

    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    #if PLD_EXPORT_FUNCS_CHECK_ID
        if (data->pld_id != LTC_SET_MODE_RSP_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, LTC_SET_MODE_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif

    cJSON *item0 = NULL;
    cJSON *item1 = NULL;
    cJSON *item2 = NULL;
    uint8_t i = 0;

    // suppress unused warnings
    (void)data;
    (void)output;

    switch (style) {
        case EXPORT_JSON_DATAONLY:
            pld_log_trace("export as data-only");
            CJSON_TRY(item0 = cJSON_CreateNumber(data->status));
            cJSON_AddItemToObjectCS(output, "status", item0);
            CJSON_TRY(item0 = cJSON_CreateArray());
            cJSON_AddItemToObjectCS(output, "error", item0);
            for (i = 0; i < 25; i++) {
                CJSON_TRY(item1 = cJSON_CreateNumber(data->error[i]));
                cJSON_AddItemToArray(item0, item1);
            }
            break;
        case EXPORT_JSON_ANNOTATED:
            pld_log_trace("export annotated");
            CJSON_TRY(item1 = cJSON_CreateObject());
            cJSON_AddItemToObjectCS(output, "status", item1);
            CJSON_TRY(item2 = cJSON_CreateStringReference("Whether the setting was valid or not"));
            cJSON_AddItemToObjectCS(item1, "descr", item2);
            CJSON_TRY(item2 = cJSON_CreateStringReference("u8"));
            cJSON_AddItemToObjectCS(item1, "type", item2);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->status));
            cJSON_AddItemToObjectCS(item1, "value", item0);
            CJSON_TRY(item0 = cJSON_CreateObject());
            cJSON_AddItemToObjectCS(output, "error", item0);
            CJSON_TRY(item1 = cJSON_CreateStringReference("In case of an error an error message"));
            cJSON_AddItemToObjectCS(item0, "descr", item1);
            CJSON_TRY(item1 = cJSON_CreateStringReference("i8[]"));
            cJSON_AddItemToObjectCS(item0, "type", item1);
            CJSON_TRY(item1 = cJSON_CreateArray());
            cJSON_AddItemToObjectCS(item0, "value", item1);
            for (i = 0; i < 25; i++) {
                CJSON_TRY(item2 = cJSON_CreateNumber(data->error[i]));
                cJSON_AddItemToArray(item1, item2);
            }
            break;
        default:
            pld_log_error("bad export style");
            return PLD_ERR_NOT_IMPLEMENTED;
    }
    return PLD_OK;
cjfail:
    return PLD_ERR_ALLOC; /* will be deallocated by caller */
}

pld_error_t LTC_SET_MODE_RSP_to_json(const struct LTC_SET_MODE_RSP *data, enum pld_export_json_style style, cJSON** output) {
    pld_log_trace("LTC_SET_MODE_RSP_to_json");
    return pld_to_json_by_spec(PldSpec_LTC_SET_MODE_RSP, data, style, output);
}

static pld_error_t LTC_GET_STATUS_REQ_to_json_inner(const struct LTC_GET_STATUS_REQ *data, enum pld_export_json_style style, cJSON* output) {
    pld_log_trace("LTC_GET_STATUS_REQ_to_json_inner");

    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    #if PLD_EXPORT_FUNCS_CHECK_ID
        if (data->pld_id != LTC_GET_STATUS_REQ_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, LTC_GET_STATUS_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif

    
    

    // suppress unused warnings
    (void)data;
    (void)output;

    switch (style) {
        case EXPORT_JSON_DATAONLY:
            pld_log_trace("export as data-only");
            
            break;
        case EXPORT_JSON_ANNOTATED:
            pld_log_trace("export annotated");
            
            break;
        default:
            pld_log_error("bad export style");
            return PLD_ERR_NOT_IMPLEMENTED;
    }
    return PLD_OK;
cjfail:
    return PLD_ERR_ALLOC; /* will be deallocated by caller */
}

pld_error_t LTC_GET_STATUS_REQ_to_json(const struct LTC_GET_STATUS_REQ *data, enum pld_export_json_style style, cJSON** output) {
    pld_log_trace("LTC_GET_STATUS_REQ_to_json");
    return pld_to_json_by_spec(PldSpec_LTC_GET_STATUS_REQ, data, style, output);
}

static pld_error_t LTC_GET_STATUS_RSP_to_json_inner(const struct LTC_GET_STATUS_RSP *data, enum pld_export_json_style style, cJSON* output) {
    pld_log_trace("LTC_GET_STATUS_RSP_to_json_inner");

    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    #if PLD_EXPORT_FUNCS_CHECK_ID
        if (data->pld_id != LTC_GET_STATUS_RSP_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, LTC_GET_STATUS_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif

    cJSON *item0 = NULL;
    cJSON *item1 = NULL;
    cJSON *item2 = NULL;
    

    // suppress unused warnings
    (void)data;
    (void)output;

    switch (style) {
        case EXPORT_JSON_DATAONLY:
            pld_log_trace("export as data-only");
            CJSON_TRY(item0 = cJSON_CreateNumber(data->mode));
            cJSON_AddItemToObjectCS(output, "mode", item0);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->result_status));
            cJSON_AddItemToObjectCS(output, "result_status", item0);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->frequency));
            cJSON_AddItemToObjectCS(output, "frequency", item0);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->error));
            cJSON_AddItemToObjectCS(output, "error", item0);
            break;
        case EXPORT_JSON_ANNOTATED:
            pld_log_trace("export annotated");
            CJSON_TRY(item1 = cJSON_CreateObject());
            cJSON_AddItemToObjectCS(output, "mode", item1);
            CJSON_TRY(item2 = cJSON_CreateStringReference("Active mode"));
            cJSON_AddItemToObjectCS(item1, "descr", item2);
            CJSON_TRY(item2 = cJSON_CreateStringReference("u8"));
            cJSON_AddItemToObjectCS(item1, "type", item2);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->mode));
            cJSON_AddItemToObjectCS(item1, "value", item0);
            CJSON_TRY(item1 = cJSON_CreateObject());
            cJSON_AddItemToObjectCS(output, "result_status", item1);
            CJSON_TRY(item2 = cJSON_CreateStringReference("Result status"));
            cJSON_AddItemToObjectCS(item1, "descr", item2);
            CJSON_TRY(item2 = cJSON_CreateStringReference("u8"));
            cJSON_AddItemToObjectCS(item1, "type", item2);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->result_status));
            cJSON_AddItemToObjectCS(item1, "value", item0);
            CJSON_TRY(item1 = cJSON_CreateObject());
            cJSON_AddItemToObjectCS(output, "frequency", item1);
            CJSON_TRY(item2 = cJSON_CreateStringReference("Continuous measurement frequency"));
            cJSON_AddItemToObjectCS(item1, "descr", item2);
            CJSON_TRY(item2 = cJSON_CreateStringReference("u32"));
            cJSON_AddItemToObjectCS(item1, "type", item2);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->frequency));
            cJSON_AddItemToObjectCS(item1, "value", item0);
            CJSON_TRY(item1 = cJSON_CreateObject());
            cJSON_AddItemToObjectCS(output, "error", item1);
            CJSON_TRY(item2 = cJSON_CreateStringReference("Error code"));
            cJSON_AddItemToObjectCS(item1, "descr", item2);
            CJSON_TRY(item2 = cJSON_CreateStringReference("u8"));
            cJSON_AddItemToObjectCS(item1, "type", item2);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->error));
            cJSON_AddItemToObjectCS(item1, "value", item0);
            break;
        default:
            pld_log_error("bad export style");
            return PLD_ERR_NOT_IMPLEMENTED;
    }
    return PLD_OK;
cjfail:
    return PLD_ERR_ALLOC; /* will be deallocated by caller */
}

pld_error_t LTC_GET_STATUS_RSP_to_json(const struct LTC_GET_STATUS_RSP *data, enum pld_export_json_style style, cJSON** output) {
    pld_log_trace("LTC_GET_STATUS_RSP_to_json");
    return pld_to_json_by_spec(PldSpec_LTC_GET_STATUS_RSP, data, style, output);
}

static pld_error_t LTC_READ_TEMP_REQ_to_json_inner(const struct LTC_READ_TEMP_REQ *data, enum pld_export_json_style style, cJSON* output) {
    pld_log_trace("LTC_READ_TEMP_REQ_to_json_inner");

    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    #if PLD_EXPORT_FUNCS_CHECK_ID
        if (data->pld_id != LTC_READ_TEMP_REQ_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, LTC_READ_TEMP_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif

    cJSON *item0 = NULL;
    cJSON *item1 = NULL;
    cJSON *item2 = NULL;
    

    // suppress unused warnings
    (void)data;
    (void)output;

    switch (style) {
        case EXPORT_JSON_DATAONLY:
            pld_log_trace("export as data-only");
            CJSON_TRY(item0 = cJSON_CreateNumber(data->channel_id));
            cJSON_AddItemToObjectCS(output, "channel_id", item0);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->force_measurement));
            cJSON_AddItemToObjectCS(output, "force_measurement", item0);
            break;
        case EXPORT_JSON_ANNOTATED:
            pld_log_trace("export annotated");
            CJSON_TRY(item1 = cJSON_CreateObject());
            cJSON_AddItemToObjectCS(output, "channel_id", item1);
            CJSON_TRY(item2 = cJSON_CreateStringReference("Target channel ID"));
            cJSON_AddItemToObjectCS(item1, "descr", item2);
            CJSON_TRY(item2 = cJSON_CreateStringReference("u8"));
            cJSON_AddItemToObjectCS(item1, "type", item2);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->channel_id));
            cJSON_AddItemToObjectCS(item1, "value", item0);
            CJSON_TRY(item1 = cJSON_CreateObject());
            cJSON_AddItemToObjectCS(output, "force_measurement", item1);
            CJSON_TRY(item2 = cJSON_CreateStringReference("Forces a new measurement if results are not ready"));
            cJSON_AddItemToObjectCS(item1, "descr", item2);
            CJSON_TRY(item2 = cJSON_CreateStringReference("u8"));
            cJSON_AddItemToObjectCS(item1, "type", item2);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->force_measurement));
            cJSON_AddItemToObjectCS(item1, "value", item0);
            break;
        default:
            pld_log_error("bad export style");
            return PLD_ERR_NOT_IMPLEMENTED;
    }
    return PLD_OK;
cjfail:
    return PLD_ERR_ALLOC; /* will be deallocated by caller */
}

pld_error_t LTC_READ_TEMP_REQ_to_json(const struct LTC_READ_TEMP_REQ *data, enum pld_export_json_style style, cJSON** output) {
    pld_log_trace("LTC_READ_TEMP_REQ_to_json");
    return pld_to_json_by_spec(PldSpec_LTC_READ_TEMP_REQ, data, style, output);
}

static pld_error_t LTC_READ_TEMP_RSP_to_json_inner(const struct LTC_READ_TEMP_RSP *data, enum pld_export_json_style style, cJSON* output) {
    pld_log_trace("LTC_READ_TEMP_RSP_to_json_inner");

    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    #if PLD_EXPORT_FUNCS_CHECK_ID
        if (data->pld_id != LTC_READ_TEMP_RSP_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, LTC_READ_TEMP_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif

    cJSON *item0 = NULL;
    cJSON *item1 = NULL;
    cJSON *item2 = NULL;
    cJSON *item3 = NULL;
    cJSON *item4 = NULL;
    cJSON *item5 = NULL;
    cJSON *item6 = NULL;
    uint8_t i = 0;

    // suppress unused warnings
    (void)data;
    (void)output;

    switch (style) {
        case EXPORT_JSON_DATAONLY:
            pld_log_trace("export as data-only");
            CJSON_TRY(item0 = cJSON_CreateNumber(data->result_ready));
            cJSON_AddItemToObjectCS(output, "result_ready", item0);
            CJSON_TRY(item0 = cJSON_CreateArray());
            cJSON_AddItemToObjectCS(output, "TempRslt", item0);
            for (i = 0; i < 20; i++) {
                CJSON_TRY(item1 = cJSON_CreateObject());
                cJSON_AddItemToArray(item0, item1);
                CJSON_TRY(item2 = cJSON_CreateNumber(data->TempRslt[i].channel));
                cJSON_AddItemToObjectCS(item1, "channel", item2);
                CJSON_TRY(item2 = cJSON_CreateNumber(data->TempRslt[i].status));
                cJSON_AddItemToObjectCS(item1, "status", item2);
                CJSON_TRY(item2 = cJSON_CreateNumber(data->TempRslt[i].temperature));
                cJSON_AddItemToObjectCS(item1, "temperature", item2);
                CJSON_TRY(item2 = cJSON_CreateNumber(data->TempRslt[i].raw));
                cJSON_AddItemToObjectCS(item1, "raw", item2);
            }
            break;
        case EXPORT_JSON_ANNOTATED:
            pld_log_trace("export annotated");
            CJSON_TRY(item1 = cJSON_CreateObject());
            cJSON_AddItemToObjectCS(output, "result_ready", item1);
            CJSON_TRY(item2 = cJSON_CreateStringReference("u8"));
            cJSON_AddItemToObjectCS(item1, "type", item2);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->result_ready));
            cJSON_AddItemToObjectCS(item1, "value", item0);
            CJSON_TRY(item0 = cJSON_CreateObject());
            cJSON_AddItemToObjectCS(output, "TempRslt", item0);
            CJSON_TRY(item1 = cJSON_CreateStringReference("struct[]"));
            cJSON_AddItemToObjectCS(item0, "type", item1);
            CJSON_TRY(item1 = cJSON_CreateArray());
            cJSON_AddItemToObjectCS(item0, "value", item1);
            for (i = 0; i < 20; i++) {
                CJSON_TRY(item2 = cJSON_CreateObject());
                cJSON_AddItemToArray(item1, item2);
                CJSON_TRY(item4 = cJSON_CreateStringReference("struct"));
                cJSON_AddItemToObjectCS(item2, "type", item4);
                CJSON_TRY(item3 = cJSON_CreateObject());
                cJSON_AddItemToObjectCS(item2, "items", item3);
                CJSON_TRY(item5 = cJSON_CreateObject());
                cJSON_AddItemToObjectCS(item3, "channel", item5);
                CJSON_TRY(item6 = cJSON_CreateStringReference("Channel ID"));
                cJSON_AddItemToObjectCS(item5, "descr", item6);
                CJSON_TRY(item6 = cJSON_CreateStringReference("u8"));
                cJSON_AddItemToObjectCS(item5, "type", item6);
                CJSON_TRY(item4 = cJSON_CreateNumber(data->TempRslt[i].channel));
                cJSON_AddItemToObjectCS(item5, "value", item4);
                CJSON_TRY(item5 = cJSON_CreateObject());
                cJSON_AddItemToObjectCS(item3, "status", item5);
                CJSON_TRY(item6 = cJSON_CreateStringReference("Status of the reading"));
                cJSON_AddItemToObjectCS(item5, "descr", item6);
                CJSON_TRY(item6 = cJSON_CreateStringReference("u8"));
                cJSON_AddItemToObjectCS(item5, "type", item6);
                CJSON_TRY(item4 = cJSON_CreateNumber(data->TempRslt[i].status));
                cJSON_AddItemToObjectCS(item5, "value", item4);
                CJSON_TRY(item5 = cJSON_CreateObject());
                cJSON_AddItemToObjectCS(item3, "temperature", item5);
                CJSON_TRY(item6 = cJSON_CreateStringReference("Temperature"));
                cJSON_AddItemToObjectCS(item5, "descr", item6);
                CJSON_TRY(item6 = cJSON_CreateStringReference("f32"));
                cJSON_AddItemToObjectCS(item5, "type", item6);
                CJSON_TRY(item4 = cJSON_CreateNumber(data->TempRslt[i].temperature));
                cJSON_AddItemToObjectCS(item5, "value", item4);
                CJSON_TRY(item5 = cJSON_CreateObject());
                cJSON_AddItemToObjectCS(item3, "raw", item5);
                CJSON_TRY(item6 = cJSON_CreateStringReference("Raw Voltage"));
                cJSON_AddItemToObjectCS(item5, "descr", item6);
                CJSON_TRY(item6 = cJSON_CreateStringReference("f32"));
                cJSON_AddItemToObjectCS(item5, "type", item6);
                CJSON_TRY(item4 = cJSON_CreateNumber(data->TempRslt[i].raw));
                cJSON_AddItemToObjectCS(item5, "value", item4);
            }
            break;
        default:
            pld_log_error("bad export style");
            return PLD_ERR_NOT_IMPLEMENTED;
    }
    return PLD_OK;
cjfail:
    return PLD_ERR_ALLOC; /* will be deallocated by caller */
}

pld_error_t LTC_READ_TEMP_RSP_to_json(const struct LTC_READ_TEMP_RSP *data, enum pld_export_json_style style, cJSON** output) {
    pld_log_trace("LTC_READ_TEMP_RSP_to_json");
    return pld_to_json_by_spec(PldSpec_LTC_READ_TEMP_RSP, data, style, output);
}

static pld_error_t LTC_SET_RSENSE_REQ_to_json_inner(const struct LTC_SET_RSENSE_REQ *data, enum pld_export_json_style style, cJSON* output) {
    pld_log_trace("LTC_SET_RSENSE_REQ_to_json_inner");

    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    #if PLD_EXPORT_FUNCS_CHECK_ID
        if (data->pld_id != LTC_SET_RSENSE_REQ_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, LTC_SET_RSENSE_REQ_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif

    cJSON *item0 = NULL;
    cJSON *item1 = NULL;
    cJSON *item2 = NULL;
    

    // suppress unused warnings
    (void)data;
    (void)output;

    switch (style) {
        case EXPORT_JSON_DATAONLY:
            pld_log_trace("export as data-only");
            CJSON_TRY(item0 = cJSON_CreateNumber(data->val));
            cJSON_AddItemToObjectCS(output, "val", item0);
            break;
        case EXPORT_JSON_ANNOTATED:
            pld_log_trace("export annotated");
            CJSON_TRY(item1 = cJSON_CreateObject());
            cJSON_AddItemToObjectCS(output, "val", item1);
            CJSON_TRY(item2 = cJSON_CreateStringReference("Rsense value to set"));
            cJSON_AddItemToObjectCS(item1, "descr", item2);
            CJSON_TRY(item2 = cJSON_CreateStringReference("f32"));
            cJSON_AddItemToObjectCS(item1, "type", item2);
            CJSON_TRY(item0 = cJSON_CreateNumber(data->val));
            cJSON_AddItemToObjectCS(item1, "value", item0);
            break;
        default:
            pld_log_error("bad export style");
            return PLD_ERR_NOT_IMPLEMENTED;
    }
    return PLD_OK;
cjfail:
    return PLD_ERR_ALLOC; /* will be deallocated by caller */
}

pld_error_t LTC_SET_RSENSE_REQ_to_json(const struct LTC_SET_RSENSE_REQ *data, enum pld_export_json_style style, cJSON** output) {
    pld_log_trace("LTC_SET_RSENSE_REQ_to_json");
    return pld_to_json_by_spec(PldSpec_LTC_SET_RSENSE_REQ, data, style, output);
}

static pld_error_t LTC_SET_RSENSE_RSP_to_json_inner(const struct LTC_SET_RSENSE_RSP *data, enum pld_export_json_style style, cJSON* output) {
    pld_log_trace("LTC_SET_RSENSE_RSP_to_json_inner");

    if (!data) {
        pld_log_error("data is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    if (!output) {
        pld_log_error("output is NULL");
        return PLD_ERR_BAD_ARGS;
    }

    #if PLD_EXPORT_FUNCS_CHECK_ID
        if (data->pld_id != LTC_SET_RSENSE_RSP_ID) {
            pld_log_error("payload ID %d does not match expected %d", data->pld_id, LTC_SET_RSENSE_RSP_ID);
            return PLD_ERR_ID_MISMATCH;
        }
    #endif

    
    

    // suppress unused warnings
    (void)data;
    (void)output;

    switch (style) {
        case EXPORT_JSON_DATAONLY:
            pld_log_trace("export as data-only");
            
            break;
        case EXPORT_JSON_ANNOTATED:
            pld_log_trace("export annotated");
            
            break;
        default:
            pld_log_error("bad export style");
            return PLD_ERR_NOT_IMPLEMENTED;
    }
    return PLD_OK;
cjfail:
    return PLD_ERR_ALLOC; /* will be deallocated by caller */
}

pld_error_t LTC_SET_RSENSE_RSP_to_json(const struct LTC_SET_RSENSE_RSP *data, enum pld_export_json_style style, cJSON** output) {
    pld_log_trace("LTC_SET_RSENSE_RSP_to_json");
    return pld_to_json_by_spec(PldSpec_LTC_SET_RSENSE_RSP, data, style, output);
}
#endif

static const struct pld_spec payload_specs[8] = {
    {
        .pld_id = LTC_SET_MODE_REQ_ID,
        .address = {
            .src = 255,
            .sport = 255,
            .dst = 13,
            .dport = 10
        },
        .bin_size = 7,
        .c_size = sizeof(struct LTC_SET_MODE_REQ),
        .growable = false,
        .tail_elem_bin_size = 0,
        .tail_elem_c_size = 0,
        .recognize = true,
        .tester = LTC_SET_MODE_REQ_test,
    #if PLD_HAVE_ALLOC
        .parse = (fn_parse_t) LTC_SET_MODE_REQ_parse,
        .build = (fn_build_t) LTC_SET_MODE_REQ_build,
    #endif /* PLD_HAVE_ALLOC */
        .parse_static = (fn_parse_static_t) LTC_SET_MODE_REQ_parse_s,
        .build_static = (fn_build_static_t) LTC_SET_MODE_REQ_build_s,
        .name = "LTC_SET_MODE_REQ",
    #if PLD_HAVE_EXPORT
        .descr = "Set measurement mode / ask for status",
        .data_to_json = (fn_data_to_json_t) LTC_SET_MODE_REQ_to_json_inner
    #endif /* PLD_HAVE_EXPORT */
    },
    {
        .pld_id = LTC_SET_MODE_RSP_ID,
        .address = {
            .src = 13,
            .sport = 10,
            .dst = 255,
            .dport = 255
        },
        .bin_size = 27,
        .c_size = sizeof(struct LTC_SET_MODE_RSP),
        .growable = false,
        .tail_elem_bin_size = 0,
        .tail_elem_c_size = 0,
        .recognize = true,
        .tester = LTC_SET_MODE_RSP_test,
    #if PLD_HAVE_ALLOC
        .parse = (fn_parse_t) LTC_SET_MODE_RSP_parse,
        .build = (fn_build_t) LTC_SET_MODE_RSP_build,
    #endif /* PLD_HAVE_ALLOC */
        .parse_static = (fn_parse_static_t) LTC_SET_MODE_RSP_parse_s,
        .build_static = (fn_build_static_t) LTC_SET_MODE_RSP_build_s,
        .name = "LTC_SET_MODE_RSP",
    #if PLD_HAVE_EXPORT
        .descr = "jeden command na set, jeden na read, flagy -s -c -t <cislo> a spol a podle bit masky se bude zjistovat\nSet mode response",
        .data_to_json = (fn_data_to_json_t) LTC_SET_MODE_RSP_to_json_inner
    #endif /* PLD_HAVE_EXPORT */
    },
    {
        .pld_id = LTC_GET_STATUS_REQ_ID,
        .address = {
            .src = 255,
            .sport = 255,
            .dst = 13,
            .dport = 10
        },
        .bin_size = 1,
        .c_size = sizeof(struct LTC_GET_STATUS_REQ),
        .growable = false,
        .tail_elem_bin_size = 0,
        .tail_elem_c_size = 0,
        .recognize = true,
        .tester = LTC_GET_STATUS_REQ_test,
    #if PLD_HAVE_ALLOC
        .parse = (fn_parse_t) LTC_GET_STATUS_REQ_parse,
        .build = (fn_build_t) LTC_GET_STATUS_REQ_build,
    #endif /* PLD_HAVE_ALLOC */
        .parse_static = (fn_parse_static_t) LTC_GET_STATUS_REQ_parse_s,
        .build_static = (fn_build_static_t) LTC_GET_STATUS_REQ_build_s,
        .name = "LTC_GET_STATUS_REQ",
    #if PLD_HAVE_EXPORT
        .descr = "Get status, mode and frequency request",
        .data_to_json = (fn_data_to_json_t) LTC_GET_STATUS_REQ_to_json_inner
    #endif /* PLD_HAVE_EXPORT */
    },
    {
        .pld_id = LTC_GET_STATUS_RSP_ID,
        .address = {
            .src = 13,
            .sport = 10,
            .dst = 255,
            .dport = 255
        },
        .bin_size = 8,
        .c_size = sizeof(struct LTC_GET_STATUS_RSP),
        .growable = false,
        .tail_elem_bin_size = 0,
        .tail_elem_c_size = 0,
        .recognize = true,
        .tester = LTC_GET_STATUS_RSP_test,
    #if PLD_HAVE_ALLOC
        .parse = (fn_parse_t) LTC_GET_STATUS_RSP_parse,
        .build = (fn_build_t) LTC_GET_STATUS_RSP_build,
    #endif /* PLD_HAVE_ALLOC */
        .parse_static = (fn_parse_static_t) LTC_GET_STATUS_RSP_parse_s,
        .build_static = (fn_build_static_t) LTC_GET_STATUS_RSP_build_s,
        .name = "LTC_GET_STATUS_RSP",
    #if PLD_HAVE_EXPORT
        .descr = "Get mode and frequency response",
        .data_to_json = (fn_data_to_json_t) LTC_GET_STATUS_RSP_to_json_inner
    #endif /* PLD_HAVE_EXPORT */
    },
    {
        .pld_id = LTC_READ_TEMP_REQ_ID,
        .address = {
            .src = 255,
            .sport = 255,
            .dst = 13,
            .dport = 10
        },
        .bin_size = 3,
        .c_size = sizeof(struct LTC_READ_TEMP_REQ),
        .growable = false,
        .tail_elem_bin_size = 0,
        .tail_elem_c_size = 0,
        .recognize = true,
        .tester = LTC_READ_TEMP_REQ_test,
    #if PLD_HAVE_ALLOC
        .parse = (fn_parse_t) LTC_READ_TEMP_REQ_parse,
        .build = (fn_build_t) LTC_READ_TEMP_REQ_build,
    #endif /* PLD_HAVE_ALLOC */
        .parse_static = (fn_parse_static_t) LTC_READ_TEMP_REQ_parse_s,
        .build_static = (fn_build_static_t) LTC_READ_TEMP_REQ_build_s,
        .name = "LTC_READ_TEMP_REQ",
    #if PLD_HAVE_EXPORT
        .descr = "LTC2983 read temperature request",
        .data_to_json = (fn_data_to_json_t) LTC_READ_TEMP_REQ_to_json_inner
    #endif /* PLD_HAVE_EXPORT */
    },
    {
        .pld_id = LTC_READ_TEMP_RSP_ID,
        .address = {
            .src = 13,
            .sport = 10,
            .dst = 255,
            .dport = 255
        },
        .bin_size = 202,
        .c_size = sizeof(struct LTC_READ_TEMP_RSP),
        .growable = false,
        .tail_elem_bin_size = 0,
        .tail_elem_c_size = 0,
        .recognize = true,
        .tester = LTC_READ_TEMP_RSP_test,
    #if PLD_HAVE_ALLOC
        .parse = (fn_parse_t) LTC_READ_TEMP_RSP_parse,
        .build = (fn_build_t) LTC_READ_TEMP_RSP_build,
    #endif /* PLD_HAVE_ALLOC */
        .parse_static = (fn_parse_static_t) LTC_READ_TEMP_RSP_parse_s,
        .build_static = (fn_build_static_t) LTC_READ_TEMP_RSP_build_s,
        .name = "LTC_READ_TEMP_RSP",
    #if PLD_HAVE_EXPORT
        .descr = "LTC2983 read temperature response",
        .data_to_json = (fn_data_to_json_t) LTC_READ_TEMP_RSP_to_json_inner
    #endif /* PLD_HAVE_EXPORT */
    },
    {
        .pld_id = LTC_SET_RSENSE_REQ_ID,
        .address = {
            .src = 255,
            .sport = 255,
            .dst = 13,
            .dport = 10
        },
        .bin_size = 5,
        .c_size = sizeof(struct LTC_SET_RSENSE_REQ),
        .growable = false,
        .tail_elem_bin_size = 0,
        .tail_elem_c_size = 0,
        .recognize = true,
        .tester = LTC_SET_RSENSE_REQ_test,
    #if PLD_HAVE_ALLOC
        .parse = (fn_parse_t) LTC_SET_RSENSE_REQ_parse,
        .build = (fn_build_t) LTC_SET_RSENSE_REQ_build,
    #endif /* PLD_HAVE_ALLOC */
        .parse_static = (fn_parse_static_t) LTC_SET_RSENSE_REQ_parse_s,
        .build_static = (fn_build_static_t) LTC_SET_RSENSE_REQ_build_s,
        .name = "LTC_SET_RSENSE_REQ",
    #if PLD_HAVE_EXPORT
        .descr = "Set rsense value",
        .data_to_json = (fn_data_to_json_t) LTC_SET_RSENSE_REQ_to_json_inner
    #endif /* PLD_HAVE_EXPORT */
    },
    {
        .pld_id = LTC_SET_RSENSE_RSP_ID,
        .address = {
            .src = 13,
            .sport = 10,
            .dst = 255,
            .dport = 255
        },
        .bin_size = 1,
        .c_size = sizeof(struct LTC_SET_RSENSE_RSP),
        .growable = false,
        .tail_elem_bin_size = 0,
        .tail_elem_c_size = 0,
        .recognize = true,
        .tester = LTC_SET_RSENSE_RSP_test,
    #if PLD_HAVE_ALLOC
        .parse = (fn_parse_t) LTC_SET_RSENSE_RSP_parse,
        .build = (fn_build_t) LTC_SET_RSENSE_RSP_build,
    #endif /* PLD_HAVE_ALLOC */
        .parse_static = (fn_parse_static_t) LTC_SET_RSENSE_RSP_parse_s,
        .build_static = (fn_build_static_t) LTC_SET_RSENSE_RSP_build_s,
        .name = "LTC_SET_RSENSE_RSP",
    #if PLD_HAVE_EXPORT
        .descr = "jeden command na set, jeden na read, flagy -s -c -t <cislo> a spol a podle bit masky se bude zjistovat\nSet rsense value response",
        .data_to_json = (fn_data_to_json_t) LTC_SET_RSENSE_RSP_to_json_inner
    #endif /* PLD_HAVE_EXPORT */
    }
};

const struct pld_module Payloads_LTC = {
    .magic = PLD_MODULE_MAGIC,
    .name = "LTC",
    .specs = payload_specs,
    .start_index = 1,
    .count = 8,
};

const struct pld_spec * const PldSpec_LTC_SET_MODE_REQ = &payload_specs[0];
const struct pld_spec * const PldSpec_LTC_SET_MODE_RSP = &payload_specs[1];
const struct pld_spec * const PldSpec_LTC_GET_STATUS_REQ = &payload_specs[2];
const struct pld_spec * const PldSpec_LTC_GET_STATUS_RSP = &payload_specs[3];
const struct pld_spec * const PldSpec_LTC_READ_TEMP_REQ = &payload_specs[4];
const struct pld_spec * const PldSpec_LTC_READ_TEMP_RSP = &payload_specs[5];
const struct pld_spec * const PldSpec_LTC_SET_RSENSE_REQ = &payload_specs[6];
const struct pld_spec * const PldSpec_LTC_SET_RSENSE_RSP = &payload_specs[7];
